#!/usr/bin/env python3
"""
Constructor.io Search Analyzer for Meijer

Analyzes Constructor.io (cnstrc.com) endpoints from meijer2.log to understand
Meijer's search backend and build comprehensive MeijerItem classes.

Generated by: Claude Sonnet 4 (claude-3-5-sonnet-20241022)
via Cursor IDE (cursor.sh) with AI assistance
"""

import json
import logging
from pathlib import Path
from typing import Dict, List, Any, Optional, Union
from collections import defaultdict, Counter
from dataclasses import dataclass, field
from datetime import datetime
from urllib.parse import urlparse, parse_qs

# Import mitmproxy modules
try:
    from mitmproxy import flow
    from mitmproxy import http
    from mitmproxy.io import FlowReader
except ImportError as e:
    print(f"Error importing mitmproxy modules: {e}")
    print("Make sure you're in the virtual environment: source venv/bin/activate")
    exit(1)


@dataclass
class ConstructorAnalysis:
    """Analysis results for Constructor.io search API calls."""

    search_calls: List[Dict[str, Any]] = field(default_factory=list)
    autocomplete_calls: List[Dict[str, Any]] = field(default_factory=list)
    browse_calls: List[Dict[str, Any]] = field(default_factory=list)
    behavior_calls: List[Dict[str, Any]] = field(default_factory=list)

    search_terms: Counter = field(default_factory=Counter)
    common_filters: Dict[str, Any] = field(default_factory=dict)
    api_parameters: Dict[str, Counter] = field(
        default_factory=lambda: defaultdict(Counter)
    )

    item_structures: List[Dict[str, Any]] = field(default_factory=list)
    unique_item_fields: Counter = field(default_factory=Counter)
    field_data_types: Dict[str, str] = field(default_factory=dict)

    api_key: Optional[str] = None
    client_id: Optional[str] = None
    session_id: Optional[str] = None


class ConstructorSearchAnalyzer:
    """
    Specialized analyzer for Constructor.io search endpoints.

    Analyzes how Meijer uses Constructor.io for search functionality
    and extracts item structures to build comprehensive MeijerItem classes.
    """

    def __init__(self, log_file_path: str):
        self.log_file_path = Path(log_file_path)
        self.flows = []
        self.analysis = ConstructorAnalysis()

        # Setup logging
        logging.basicConfig(level=logging.INFO)
        self.logger = logging.getLogger(__name__)

        # Constructor.io endpoint patterns
        self.constructor_endpoints = {
            "search": "/search/",
            "autocomplete": "/autocomplete/",
            "browse": "/browse/",
            "behavior": "/behavior",
            "behavioral_action": "/behavioral_action/",
            "v2/behavioral_action": "/v2/behavioral_action/",
        }

    def load_flows(self) -> bool:
        """Load flows from the mitmproxy log file."""
        try:
            if not self.log_file_path.exists():
                self.logger.error(f"Log file not found: {self.log_file_path}")
                return False

            self.logger.info(f"Loading flows from: {self.log_file_path}")

            with open(self.log_file_path, "rb") as f:
                reader = FlowReader(f)

                flow_count = 0
                for flow_obj in reader.stream():
                    self.flows.append(flow_obj)
                    flow_count += 1

                    if flow_count % 1000 == 0:
                        self.logger.info(f"Loaded {flow_count} flows...")

                self.logger.info(f"Successfully loaded {len(self.flows)} flows")
                return True

        except Exception as e:
            self.logger.error(f"Error loading flows: {e}")
            return False

    def analyze_constructor_flows(self) -> None:
        """Analyze flows specifically for Constructor.io endpoints."""
        self.logger.info("Starting Constructor.io flow analysis...")

        constructor_flow_count = 0

        for i, flow_obj in enumerate(self.flows):
            try:
                if not isinstance(flow_obj, http.HTTPFlow):
                    continue

                request = flow_obj.request
                response = flow_obj.response

                if not hasattr(request, "pretty_url") or not request.pretty_url:
                    continue

                url_str = request.pretty_url

                # Check if this is a Constructor.io endpoint
                if "cnstrc.com" in url_str:
                    constructor_flow_count += 1
                    endpoint_type = self._get_constructor_endpoint_type(url_str)
                    self._analyze_constructor_flow(flow_obj, endpoint_type)

                if (i + 1) % 1000 == 0:
                    self.logger.info(f"Analyzed {i + 1}/{len(self.flows)} flows...")

            except Exception as e:
                self.logger.error(f"Error analyzing flow {i}: {e}")

        self.logger.info(f"Found {constructor_flow_count} Constructor.io flows")
        self._analyze_patterns()

    def _get_constructor_endpoint_type(self, url_str: str) -> Optional[str]:
        """Determine the Constructor.io endpoint type."""
        for endpoint_path, endpoint_type in self.constructor_endpoints.items():
            if endpoint_path in url_str:
                return endpoint_type.replace("/", "")
        return "unknown"

    def _analyze_constructor_flow(
        self, flow_obj: http.HTTPFlow, endpoint_type: str
    ) -> None:
        """Analyze a single Constructor.io flow."""
        request = flow_obj.request
        response = flow_obj.response

        # Parse URL components
        parsed_url = urlparse(request.pretty_url)
        query_params = parse_qs(parsed_url.query)

        # Extract common parameters
        api_key = query_params.get("key", [None])[0]
        client_id = query_params.get("i", [None])[0]
        session_id = query_params.get("s", [None])[0]

        if api_key and not self.analysis.api_key:
            self.analysis.api_key = api_key
        if client_id and not self.analysis.client_id:
            self.analysis.client_id = client_id
        if session_id and not self.analysis.session_id:
            self.analysis.session_id = session_id

        flow_data = {
            "url": request.pretty_url,
            "method": request.method,
            "status_code": response.status_code if response else None,
            "timestamp": getattr(flow_obj, "timestamp_start", None),
            "path": parsed_url.path,
            "query_params": query_params,
            "request_headers": dict(request.headers)
            if hasattr(request, "headers")
            else {},
            "response_headers": dict(response.headers)
            if response and hasattr(response, "headers")
            else {},
            "request_body": self._extract_and_parse_body(request),
            "response_body": self._extract_and_parse_body(response)
            if response
            else None,
        }

        # Store flow data by endpoint type
        if endpoint_type == "search":
            self.analysis.search_calls.append(flow_data)
            # Extract search term
            search_term = self._extract_search_term(flow_data)
            if search_term:
                self.analysis.search_terms[search_term] += 1

        elif endpoint_type == "autocomplete":
            self.analysis.autocomplete_calls.append(flow_data)
            # Extract search term from autocomplete
            search_term = self._extract_search_term(flow_data)
            if search_term:
                self.analysis.search_terms[search_term] += 1

        elif endpoint_type == "browse":
            self.analysis.browse_calls.append(flow_data)

        elif endpoint_type in ["behavior", "behavioral_action", "v2/behavioral_action"]:
            self.analysis.behavior_calls.append(flow_data)

        # Track API parameters
        for param, values in query_params.items():
            if values:
                self.analysis.api_parameters[param][values[0]] += 1

        # Extract item structures from response
        if response and flow_data["response_body"]:
            self._extract_item_structures(flow_data["response_body"], endpoint_type)

    def _extract_search_term(self, flow_data: Dict[str, Any]) -> Optional[str]:
        """Extract search term from flow data."""
        # From URL path
        path = flow_data.get("path", "")
        if "/search/" in path:
            # Path like /search/milk
            term = path.split("/search/")[-1].split("?")[0]
            if term and term != "search":
                return term
        elif "/autocomplete/" in path:
            # Path like /autocomplete/milk
            term = path.split("/autocomplete/")[-1].split("?")[0]
            if term and term != "autocomplete":
                return term

        # From query parameters
        query_params = flow_data.get("query_params", {})
        if "term" in query_params:
            term = query_params["term"][0] if query_params["term"] else None
            if term:
                return term

        return None

    def _extract_and_parse_body(self, http_obj) -> Union[Dict, List, str, None]:
        """Extract and parse HTTP body content."""
        try:
            if hasattr(http_obj, "content") and http_obj.content:
                try:
                    text_content = http_obj.content.decode("utf-8")
                    try:
                        return json.loads(text_content)
                    except json.JSONDecodeError:
                        return text_content
                except UnicodeDecodeError:
                    hex_content = http_obj.content.hex()
                    return (
                        hex_content[:200] + "..."
                        if len(hex_content) > 200
                        else hex_content
                    )
        except Exception:
            pass
        return None

    def _extract_item_structures(
        self, response_data: Union[Dict, List, str], endpoint_type: str
    ) -> None:
        """Extract and analyze item structures from Constructor.io responses."""
        if not isinstance(response_data, dict):
            return

        # Look for results/items in different response structures
        items = []

        # Common Constructor.io response structures
        if "results" in response_data:
            items = response_data["results"]
        elif "response" in response_data and isinstance(
            response_data["response"], dict
        ):
            resp = response_data["response"]
            if "results" in resp:
                items = resp["results"]
            elif "products" in resp:
                items = resp["products"]
        elif "sections" in response_data:
            # Autocomplete responses have sections
            for section in response_data["sections"]:
                if "options" in section:
                    items.extend(section["options"])

        # Analyze each item
        for item in items:
            if isinstance(item, dict):
                self._analyze_single_item(item, endpoint_type)
                self.analysis.item_structures.append(item)

    def _analyze_single_item(self, item: Dict[str, Any], endpoint_type: str) -> None:
        """Analyze a single item structure to understand fields and types."""

        # Flatten nested structures for field analysis
        def flatten_dict(d, parent_key="", sep="_"):
            """Flatten nested dictionary."""
            items = []
            for k, v in d.items():
                new_key = f"{parent_key}{sep}{k}" if parent_key else k
                if isinstance(v, dict):
                    items.extend(flatten_dict(v, new_key, sep=sep).items())
                elif isinstance(v, list) and v and isinstance(v[0], dict):
                    # For lists of dicts, analyze the first item
                    items.extend(flatten_dict(v[0], f"{new_key}_item", sep=sep).items())
                else:
                    items.append((new_key, v))
            return dict(items)

        flattened = flatten_dict(item)

        # Analyze all fields
        for field_name, field_value in flattened.items():
            # Count field frequency
            self.analysis.unique_item_fields[field_name] += 1

            # Determine and store data type
            field_type = type(field_value).__name__
            if field_name not in self.analysis.field_data_types:
                self.analysis.field_data_types[field_name] = field_type
            elif self.analysis.field_data_types[field_name] != field_type:
                # Handle mixed types
                existing_type = self.analysis.field_data_types[field_name]
                if not existing_type.startswith("Union"):
                    self.analysis.field_data_types[field_name] = (
                        f"Union[{existing_type}, {field_type}]"
                    )

    def _analyze_patterns(self) -> None:
        """Analyze patterns in Constructor.io API usage."""
        # Extract common filters
        all_search_calls = self.analysis.search_calls + self.analysis.browse_calls

        filters = defaultdict(Counter)
        for call in all_search_calls:
            query_params = call.get("query_params", {})
            for param, values in query_params.items():
                if param.startswith("filters[") and values:
                    filter_name = param.replace("filters[", "").replace("]", "")
                    filters[filter_name][values[0]] += 1

        self.analysis.common_filters = dict(filters)

    def generate_meijer_item_class(self) -> str:
        """Generate MeijerItem class based on analyzed item structures."""
        # Get the most common fields
        sorted_fields = sorted(
            self.analysis.unique_item_fields.items(), key=lambda x: x[1], reverse=True
        )

        class_definition = '''#!/usr/bin/env python3
"""
MeijerItem class generated from Constructor.io search API analysis.

This class represents items returned from Meijer's search backend (Constructor.io)
and includes all discovered fields from the search API responses.

Generated by analyzing meijer2.log Constructor.io endpoints.
"""

from typing import Optional, Union, List, Dict, Any, TYPE_CHECKING
from dataclasses import dataclass, field
from datetime import datetime
import json
import logging

if TYPE_CHECKING:
    from meijer_comprehensive import MeijerComprehensiveClient

logger = logging.getLogger(__name__)


@dataclass
class MeijerItem:
    """
    Represents a Meijer product item from search results.
    
    This class contains all fields discovered from Constructor.io API analysis
    and provides methods for interacting with individual items.
    """
    
'''

        # Add field definitions based on analysis
        core_fields = ["value", "data", "id"]  # Prioritize core fields

        # Add core fields first
        for field_name, frequency in sorted_fields:
            if any(core in field_name.lower() for core in core_fields):
                field_type = self._convert_to_python_type(
                    self.analysis.field_data_types.get(field_name, "Any")
                )
                python_field_name = self._to_snake_case(field_name)

                # Determine if field should be optional
                total_items = len(self.analysis.item_structures)
                is_optional = frequency < total_items * 0.8  # Less than 80% presence

                if is_optional and not field_type.startswith("Optional"):
                    field_type = f"Optional[{field_type}]"

                default_value = " = None" if is_optional else ""
                class_definition += (
                    f"    {python_field_name}: {field_type}{default_value}\n"
                )

        # Add other important fields
        for field_name, frequency in sorted_fields[:30]:  # Top 30 fields
            if not any(core in field_name.lower() for core in core_fields):
                field_type = self._convert_to_python_type(
                    self.analysis.field_data_types.get(field_name, "Any")
                )
                python_field_name = self._to_snake_case(field_name)

                # Skip if already added
                if python_field_name in class_definition:
                    continue

                total_items = len(self.analysis.item_structures)
                is_optional = frequency < total_items * 0.8

                if is_optional and not field_type.startswith("Optional"):
                    field_type = f"Optional[{field_type}]"

                default_value = " = None" if is_optional else ""
                class_definition += (
                    f"    {python_field_name}: {field_type}{default_value}\n"
                )

        # Add the search client field
        class_definition += "\n    # Internal fields\n"
        class_definition += '    _meijer_client: Optional["MeijerComprehensiveClient"] = field(default=None, repr=False)\n'
        class_definition += "    _raw_data: Optional[Dict[str, Any]] = field(default=None, repr=False)\n"

        # Add methods
        class_definition += '''
    @classmethod
    def from_constructor_response(cls, item_data: Dict[str, Any], client: Optional["MeijerComprehensiveClient"] = None) -> "MeijerItem":
        """
        Create a MeijerItem from Constructor.io API response data.
        
        Args:
            item_data: Raw item data from Constructor.io search response
            client: Meijer client for additional operations
            
        Returns:
            MeijerItem instance
        """
        # Extract common Constructor.io fields
        value = item_data.get('value', '')
        data = item_data.get('data', {})
        
        # Create instance with discovered field mappings
        kwargs = {
            '_meijer_client': client,
            '_raw_data': item_data
        }
        
        # Map common fields
        field_mappings = {'''

        # Add field mappings for common Constructor.io fields
        common_mappings = [
            ("value", "title"),
            ("data_id", "product_id"),
            ("data_price", "price"),
            ("data_image_url", "image_url"),
            ("data_description", "description"),
            ("data_brand", "brand"),
            ("data_url", "product_url"),
        ]

        for src_field, dst_field in common_mappings:
            class_definition += (
                f"\n            '{dst_field}': item_data.get('{src_field}'),"
            )

        class_definition += '''
        }
        
        # Apply field mappings
        for field_name, value in field_mappings.items():
            if hasattr(cls, field_name):
                kwargs[field_name] = value
        
        return cls(**{k: v for k, v in kwargs.items() if v is not None})
    
    @property
    def title(self) -> str:
        """Get the item title/name."""
        return getattr(self, 'value', '') or getattr(self, 'title', '') or 'Unknown Item'
    
    @property
    def product_id(self) -> Optional[str]:
        """Get the product ID."""
        if hasattr(self, 'data_id'):
            return getattr(self, 'data_id', None)
        return getattr(self, 'id', None)
    
    @property
    def price(self) -> Optional[float]:
        """Get the item price."""
        price_val = getattr(self, 'data_price', None)
        if price_val:
            try:
                return float(price_val)
            except (ValueError, TypeError):
                pass
        return None
    
    @property
    def image_url(self) -> Optional[str]:
        """Get the item image URL."""
        return getattr(self, 'data_image_url', None)
    
    @property
    def brand(self) -> Optional[str]:
        """Get the item brand."""
        return getattr(self, 'data_brand', None)
    
    def add_to_cart(self, quantity: int = 1) -> bool:
        """
        Add this item to the shopping cart.
        
        Args:
            quantity: Number of items to add
            
        Returns:
            True if successful, False otherwise
        """
        if not self._meijer_client:
            logger.warning("No Meijer client associated with item")
            return False
        
        # This would need implementation in the Meijer client
        if hasattr(self._meijer_client, 'add_to_cart'):
            return self._meijer_client.add_to_cart(self.product_id, quantity)
        
        logger.warning("Meijer client does not support add_to_cart")
        return False
    
    def get_detailed_info(self) -> Dict[str, Any]:
        """
        Get detailed product information.
        
        Returns:
            Dictionary with detailed product data
        """
        if self._raw_data:
            return self._raw_data
        
        # Return basic info from current fields
        return {
            'title': self.title,
            'product_id': self.product_id,
            'price': self.price,
            'image_url': self.image_url,
            'brand': self.brand
        }
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert item to dictionary representation."""
        result = {}
        for field_name, field_value in self.__dict__.items():
            if field_name.startswith('_'):
                continue
            result[field_name] = field_value
        return result
    
    def __str__(self) -> str:
        """String representation of the item."""
        price_str = f"${self.price:.2f}" if self.price else "Price N/A"
        brand_str = f" by {self.brand}" if self.brand else ""
        return f"MeijerItem({self.title}{brand_str}) - {price_str}"
    
    def __repr__(self) -> str:
        """Detailed representation of the item."""
        return f"MeijerItem(id={self.product_id}, title='{self.title}', price={self.price})"


# Factory function for creating MeijerItem lists from search responses
def create_meijer_items_from_search(search_response: Dict[str, Any], client: Optional["MeijerComprehensiveClient"] = None) -> List[MeijerItem]:
    """
    Create a list of MeijerItem objects from Constructor.io search response.
    
    Args:
        search_response: Response from Constructor.io search API
        client: Meijer client for additional operations
        
    Returns:
        List of MeijerItem objects
    """
    items = []
    
    # Handle different Constructor.io response structures
    results = []
    if isinstance(search_response, dict):
        if 'results' in search_response:
            results = search_response['results']
        elif 'response' in search_response and isinstance(search_response['response'], dict):
            resp = search_response['response']
            if 'results' in resp:
                results = resp['results']
    
    for item_data in results:
        try:
            item = MeijerItem.from_constructor_response(item_data, client)
            items.append(item)
        except Exception as e:
            logger.error(f"Failed to create MeijerItem from data: {e}")
            continue
    
    return items


if __name__ == "__main__":
    print("MeijerItem class generated from Constructor.io API analysis")
    print(f"Based on analysis of Constructor.io search endpoints")
'''

        return class_definition

    def _convert_to_python_type(self, type_str: str) -> str:
        """Convert discovered types to proper Python types."""
        type_map = {
            "str": "str",
            "int": "int",
            "float": "float",
            "bool": "bool",
            "list": "List[Any]",
            "dict": "Dict[str, Any]",
            "NoneType": "None",
        }

        if type_str.startswith("Union["):
            return type_str

        return type_map.get(type_str, "Any")

    def _to_snake_case(self, camel_str: str) -> str:
        """Convert camelCase or other formats to snake_case."""
        import re

        # Handle data_field patterns
        if camel_str.startswith("data_"):
            return camel_str.lower()

        # Convert camelCase
        s1 = re.sub("(.)([A-Z][a-z]+)", r"\1_\2", camel_str)
        s2 = re.sub("([a-z0-9])([A-Z])", r"\1_\2", s1)
        return s2.lower().replace("-", "_").replace(" ", "_")

    def generate_search_function(self) -> str:
        """Generate search function based on Constructor.io API patterns."""

        # Analyze search parameters from the flows
        search_function = '''#!/usr/bin/env python3
"""
Meijer Search Function using Constructor.io backend.

Generated from analysis of Constructor.io API calls in meijer2.log.
"""

from typing import List, Optional, Dict, Any
import requests
import json
import logging
from urllib.parse import urlencode

from meijer_item import MeijerItem, create_meijer_items_from_search

logger = logging.getLogger(__name__)


class MeijerSearch:
    """
    Meijer search functionality using Constructor.io backend.
    
    This class provides search, autocomplete, and browse functionality
    by interfacing with Meijer's Constructor.io search backend.
    """
    
    def __init__(self, meijer_client=None):
        """
        Initialize the search interface.
        
        Args:
            meijer_client: Associated Meijer client for authentication
        """
        self.meijer_client = meijer_client
        
        # Constructor.io configuration (discovered from analysis)'''

        if self.analysis.api_key:
            search_function += f'\n        self.api_key = "{self.analysis.api_key}"'
        else:
            search_function += '\n        self.api_key = "key_GdYuTcnduTUtsZd6"  # Default from analysis'

        search_function += """
        self.base_url = "https://ac.cnstrc.com"
        self.client_id = None  # Will be set from meijer_client
        self.session_id = None
        
        # Common parameters from analysis
        self.default_params = {
            "c": "cioand-2.31.0",  # Client version
            "num_results_per_page": 30,
            "page": 1
        }
        
        # Common filters discovered from analysis
        self.default_filters = {"""

        # Add discovered filters
        if "availableInStores" in self.analysis.common_filters:
            stores = list(self.analysis.common_filters["availableInStores"].keys())
            if stores:
                search_function += (
                    f'\n            "availableInStores": "{stores[0]}"  # Store filter'
                )

        search_function += '''
        }
    
    def search(self, 
               query: str, 
               page: int = 1, 
               results_per_page: int = 30,
               filters: Optional[Dict[str, str]] = None,
               store_id: Optional[str] = None) -> List[MeijerItem]:
        """
        Search for products using Constructor.io backend.
        
        Args:
            query: Search term
            page: Page number (1-based)
            results_per_page: Number of results per page
            filters: Additional filters to apply
            store_id: Store ID for availability filtering
            
        Returns:
            List of MeijerItem objects
        """
        endpoint = f"{self.base_url}/search/{query}"
        
        # Build parameters
        params = {
            "key": self.api_key,
            "page": page,
            "num_results_per_page": results_per_page,
            **self.default_params
        }
        
        # Add client and session info if available
        if self.meijer_client:
            if hasattr(self.meijer_client, '_digital_id'):
                params["i"] = self.meijer_client._digital_id
            if hasattr(self.meijer_client, '_session_id'):
                params["s"] = self.meijer_client._session_id
        
        # Add filters
        applied_filters = {**self.default_filters}
        if filters:
            applied_filters.update(filters)
        if store_id:
            applied_filters["availableInStores"] = store_id
            
        # Convert filters to Constructor.io format
        for filter_name, filter_value in applied_filters.items():
            params[f"filters[{filter_name}]"] = filter_value
        
        try:
            response = requests.get(endpoint, params=params)
            response.raise_for_status()
            
            search_data = response.json()
            items = create_meijer_items_from_search(search_data, self.meijer_client)
            
            logger.info(f"Search for '{query}' returned {len(items)} items")
            return items
            
        except Exception as e:
            logger.error(f"Search failed for '{query}': {e}")
            return []
    
    def autocomplete(self, 
                     partial_query: str, 
                     num_suggestions: int = 8) -> List[str]:
        """
        Get autocomplete suggestions for a partial query.
        
        Args:
            partial_query: Partial search term
            num_suggestions: Number of suggestions to return
            
        Returns:
            List of suggested search terms
        """
        endpoint = f"{self.base_url}/autocomplete/{partial_query}"
        
        params = {
            "key": self.api_key,
            "num_results_Search%20Suggestions": num_suggestions,
            "num_results_Products": 0,  # We want suggestions, not products
            **self.default_params
        }
        
        # Add client info if available
        if self.meijer_client:
            if hasattr(self.meijer_client, '_digital_id'):
                params["i"] = self.meijer_client._digital_id
        
        try:
            response = requests.get(endpoint, params=params)
            response.raise_for_status()
            
            data = response.json()
            suggestions = []
            
            # Extract suggestions from Constructor.io response
            if 'sections' in data:
                for section in data['sections']:
                    if section.get('display_name') == 'Search Suggestions':
                        for option in section.get('options', []):
                            suggestions.append(option.get('value', ''))
            
            return suggestions[:num_suggestions]
            
        except Exception as e:
            logger.error(f"Autocomplete failed for '{partial_query}': {e}")
            return []
    
    def browse_category(self, 
                       collection_id: str,
                       page: int = 1,
                       results_per_page: int = 30,
                       filters: Optional[Dict[str, str]] = None) -> List[MeijerItem]:
        """
        Browse products by category/collection.
        
        Args:
            collection_id: Constructor.io collection identifier
            page: Page number
            results_per_page: Number of results per page
            filters: Additional filters
            
        Returns:
            List of MeijerItem objects
        """
        endpoint = f"{self.base_url}/browse/collection_id/{collection_id}"
        
        params = {
            "key": self.api_key,
            "page": page,
            "num_results_per_page": results_per_page,
            **self.default_params
        }
        
        # Add filters
        applied_filters = {**self.default_filters}
        if filters:
            applied_filters.update(filters)
            
        for filter_name, filter_value in applied_filters.items():
            params[f"filters[{filter_name}]"] = filter_value
        
        try:
            response = requests.get(endpoint, params=params)
            response.raise_for_status()
            
            browse_data = response.json()
            items = create_meijer_items_from_search(browse_data, self.meijer_client)
            
            logger.info(f"Browse category '{collection_id}' returned {len(items)} items")
            return items
            
        except Exception as e:
            logger.error(f"Browse failed for category '{collection_id}': {e}")
            return []
    
    def get_popular_searches(self) -> List[str]:
        """
        Get popular search terms based on analysis.
        
        Returns:
            List of popular search terms
        """
        # Return popular terms discovered from log analysis'''

        # Add popular search terms from analysis
        if self.analysis.search_terms:
            popular_terms = [
                term for term, count in self.analysis.search_terms.most_common(10)
            ]
            search_function += f"\n        popular_terms = {popular_terms}"
        else:
            search_function += '\n        popular_terms = ["milk", "bread", "eggs", "chicken", "bananas"]'

        search_function += '''
        return popular_terms
    
    def track_search_behavior(self, 
                             search_term: str, 
                             num_results: int, 
                             customer_ids: Optional[List[str]] = None):
        """
        Track search behavior for analytics (observed in Constructor.io calls).
        
        Args:
            search_term: The search term used
            num_results: Number of results returned
            customer_ids: List of customer IDs that were clicked/viewed
        """
        endpoint = f"{self.base_url}/behavior"
        
        params = {
            "key": self.api_key,
            "term": search_term,
            "num_results": num_results,
            "action": "search-results",
            **self.default_params
        }
        
        if customer_ids:
            params["customer_ids"] = ",".join(customer_ids)
        
        try:
            response = requests.get(endpoint, params=params)
            # Don't raise for status - analytics calls may return 204
            logger.debug(f"Tracked search behavior for '{search_term}'")
            
        except Exception as e:
            logger.warning(f"Failed to track search behavior: {e}")


# Integration with main Meijer client
class MeijerWithSearch:
    """
    Extended Meijer client with search functionality.
    """
    
    def __init__(self, meijer_client):
        """Initialize with existing Meijer client."""
        self.meijer_client = meijer_client
        self.search = MeijerSearch(meijer_client)
    
    def search_products(self, query: str, **kwargs) -> List[MeijerItem]:
        """Search for products."""
        return self.search.search(query, **kwargs)
    
    def get_autocomplete(self, partial_query: str, **kwargs) -> List[str]:
        """Get autocomplete suggestions."""
        return self.search.autocomplete(partial_query, **kwargs)
    
    def browse_category(self, category: str, **kwargs) -> List[MeijerItem]:
        """Browse products by category."""
        return self.search.browse_category(category, **kwargs)


if __name__ == "__main__":
    # Example usage
    search = MeijerSearch()
    
    # Search for products
    results = search.search("milk")
    print(f"Found {len(results)} results for 'milk'")
    
    for item in results[:5]:
        print(f"  - {item}")
    
    # Get autocomplete suggestions
    suggestions = search.autocomplete("mil")
    print(f"Autocomplete suggestions: {suggestions}")
'''

        return search_function

    def generate_report(self) -> Dict[str, Any]:
        """Generate comprehensive analysis report."""
        return {
            "summary": {
                "total_flows_analyzed": len(self.flows),
                "constructor_search_calls": len(self.analysis.search_calls),
                "constructor_autocomplete_calls": len(self.analysis.autocomplete_calls),
                "constructor_browse_calls": len(self.analysis.browse_calls),
                "constructor_behavior_calls": len(self.analysis.behavior_calls),
                "unique_search_terms": len(self.analysis.search_terms),
                "unique_item_fields": len(self.analysis.unique_item_fields),
                "total_items_analyzed": len(self.analysis.item_structures),
            },
            "api_configuration": {
                "api_key": self.analysis.api_key,
                "client_id": self.analysis.client_id,
                "session_id": self.analysis.session_id,
                "base_url": "https://ac.cnstrc.com",
            },
            "search_terms": dict(self.analysis.search_terms.most_common(20)),
            "common_filters": self.analysis.common_filters,
            "api_parameters": {
                k: dict(v.most_common(5))
                for k, v in self.analysis.api_parameters.items()
            },
            "item_field_analysis": {
                "most_common_fields": dict(
                    self.analysis.unique_item_fields.most_common(30)
                ),
                "field_data_types": self.analysis.field_data_types,
            },
            "sample_items": self.analysis.item_structures[:5]
            if self.analysis.item_structures
            else [],
            "endpoint_analysis": {
                "search_endpoint": "/search/{query}",
                "autocomplete_endpoint": "/autocomplete/{partial_query}",
                "browse_endpoint": "/browse/collection_id/{collection_id}",
                "behavior_endpoint": "/behavior",
            },
        }

    def save_report(
        self, output_file: str = "constructor_search_analysis.json"
    ) -> None:
        """Save the analysis report to a JSON file."""
        try:
            report = self.generate_report()

            with open(output_file, "w") as f:
                json.dump(report, f, indent=2, default=str)

            self.logger.info(f"Constructor.io analysis report saved to: {output_file}")

        except Exception as e:
            self.logger.error(f"Error saving report: {e}")

    def save_meijer_item_class(self, output_file: str = "meijer_item.py") -> None:
        """Save the generated MeijerItem class to a Python file."""
        try:
            class_definition = self.generate_meijer_item_class()

            with open(output_file, "w") as f:
                f.write(class_definition)

            self.logger.info(f"MeijerItem class saved to: {output_file}")

        except Exception as e:
            self.logger.error(f"Error saving MeijerItem class: {e}")

    def save_search_function(self, output_file: str = "meijer_search.py") -> None:
        """Save the generated search function to a Python file."""
        try:
            search_function = self.generate_search_function()

            with open(output_file, "w") as f:
                f.write(search_function)

            self.logger.info(f"Meijer search function saved to: {output_file}")

        except Exception as e:
            self.logger.error(f"Error saving search function: {e}")

    def print_summary(self) -> None:
        """Print a summary of the Constructor.io analysis."""
        report = self.generate_report()
        summary = report["summary"]

        print("\n" + "=" * 80)
        print("🔍 CONSTRUCTOR.IO SEARCH ANALYSIS SUMMARY")
        print("=" * 80)

        print(f"📊 Total Flows Analyzed: {summary['total_flows_analyzed']:,}")
        print(f"🔍 Search API Calls: {summary['constructor_search_calls']:,}")
        print(f"💡 Autocomplete Calls: {summary['constructor_autocomplete_calls']:,}")
        print(f"📂 Browse Calls: {summary['constructor_browse_calls']:,}")
        print(f"📈 Behavior Tracking Calls: {summary['constructor_behavior_calls']:,}")
        print(f"🏷️  Unique Search Terms: {summary['unique_search_terms']:,}")
        print(f"🛍️  Items Analyzed: {summary['total_items_analyzed']:,}")
        print(f"🔑 Unique Item Fields: {summary['unique_item_fields']:,}")

        print("\n🔧 API Configuration:")
        config = report["api_configuration"]
        print(f"   Base URL: {config['base_url']}")
        print(f"   API Key: {config['api_key']}")
        print(f"   Client ID: {config['client_id']}")

        print("\n🔍 Popular Search Terms:")
        for term, count in list(report["search_terms"].items())[:10]:
            print(f"   '{term}': {count} searches")

        print("\n🏷️  Most Common Item Fields:")
        for field, count in list(
            report["item_field_analysis"]["most_common_fields"].items()
        )[:10]:
            field_type = report["item_field_analysis"]["field_data_types"].get(
                field, "Unknown"
            )
            print(f"   {field} ({field_type}): appears in {count} items")

        if report["common_filters"]:
            print("\n🔗 Common Filters:")
            for filter_name, values in report["common_filters"].items():
                top_value = list(values.items())[0] if values else ("N/A", 0)
                print(f"   {filter_name}: {top_value[0]} ({top_value[1]} uses)")

        print("\n" + "=" * 80)


def main():
    """Main function to analyze Constructor.io search endpoints in meijer2.log."""
    print("🔍 Constructor.io Search Analyzer")
    print("=" * 60)

    # Initialize analyzer with meijer2.log
    analyzer = ConstructorSearchAnalyzer("meijer2.log")

    # Load flows
    print("📂 Loading flows from meijer2.log...")
    if not analyzer.load_flows():
        print("❌ Failed to load flows. Exiting.")
        return

    # Analyze Constructor.io flows
    print("🔍 Analyzing Constructor.io search flows...")
    analyzer.analyze_constructor_flows()

    # Generate and display report
    print("📊 Generating Constructor.io analysis report...")
    analyzer.print_summary()

    # Save detailed report
    print("💾 Saving detailed analysis report...")
    analyzer.save_report()

    # Generate and save MeijerItem class
    print("🏗️  Generating MeijerItem class...")
    analyzer.save_meijer_item_class()

    # Generate and save search function
    print("🔍 Generating Meijer search function...")
    analyzer.save_search_function()

    print("\n✅ Constructor.io analysis completed successfully!")
    print("📄 Check 'constructor_search_analysis.json' for detailed results")
    print("🐍 Check 'meijer_item.py' for the generated MeijerItem class")
    print("🔍 Check 'meijer_search.py' for the search functionality")


if __name__ == "__main__":
    main()
