#!/usr/bin/env python3
"""
MeijerStore class generated from storeInfo API analysis.

This class represents Meijer store information returned from storeInfo endpoints
and includes all discovered fields from the API responses.

Generated by analyzing meijer2.log storeInfo endpoints.
"""

from typing import Optional, Union, List, Dict, Any, TYPE_CHECKING
from dataclasses import dataclass, field
from datetime import datetime
import json
import logging

if TYPE_CHECKING:
    from meijer_comprehensive import MeijerComprehensiveClient

logger = logging.getLogger(__name__)


@dataclass
class MeijerStore:
    """
    Represents a Meijer store from storeInfo API results.
    
    This class contains all fields discovered from storeInfo API analysis
    and provides methods for interacting with store information.
    """
    
    mfc_phone_number: Union[NoneType, str]
    holiday_info: None
    dlvry_order_holiday_open: str
    dlvry_order_holiday_close: str
    dlvry_order_phone: Union[NoneType, str]
    pharm_drive_thru_holiday_open: Union[NoneType, str]
    pharm_drive_thru_holiday_close: Union[NoneType, str]
    fulfillment_info_item__unit_id: int
    fulfillment_info_item__fulfillment_type_name: str
    fulfillment_info_item__fulfillment_type_id: int
    fulfillment_info_item__fulfillment_partner_name: str
    fulfillment_info_item__fulfillment_partner_id: int
    mfc_unit_id: Union[NoneType, str]
    unit_id: int
    address: str
    phone_number: str
    name: str
    pharm_holiday_open: str
    pharm_holiday_close: str
    pharm_address: str
    pharm_phone: str
    store_dir_name: Union[str, NoneType]
    store_dir_emp_id: Union[str, NoneType]
    pre_order_phone: str
    curbside_allow: str
    curbside_phone: str
    curbside_drive_thru: str
    curbside_weekday_open: str
    curbside_weekday_close: str
    curbside_sat_open: str
    curbside_sat_close: str
    curbside_sun_open: str
    curbside_sun_close: str
    curbside_holiday_open: str
    curbside_holiday_close: str
    curbside_instore_allow: str
    pre_order_holiday_open: str
    pre_order_holiday_close: str
    aurus_merchant_id: Union[NoneType, str]
    aurus_terminal_id: Union[NoneType, str]
    deli_order_holiday_open: str
    deli_order_holiday_close: str
    deli_order_phone: Union[NoneType, str]
    deli_description: Union[NoneType, str]
    pharm_drive_through_holiday_open: None
    pharm_drive_through_holiday_close: None
    tenants_item__name: str
    tenants_item__phone: str
    gas_station_amenities_item__unit_id: int
    gas_station_amenities_item__auxiliary_unit_id: int
    gas_station_amenities_item__amentity_type: str
    gas_station_amenities_item__amentity_group_type: str
    aux_unit_info__aux_unit_id: Optional[int] = None
    aux_unit_info__unit_id: Optional[int] = None
    aux_unit_info__address: Optional[str] = None
    aux_unit_info__address_line2: Optional[str] = None
    aux_unit_info__long_name: Optional[str] = None
    aux_unit_info__short_name: Optional[str] = None
    aux_unit_info__phone_number: Optional[str] = None
    aux_unit_info__aux_unit_type_id: Optional[int] = None
    gas_station_amenities: Optional[None] = None
    market_and_region__market_id: Optional[int] = None
    market_and_region__region_id: Optional[int] = None
    is_alcohol_pickupable: Union[NoneType, bool]
    is_alcohol_deliverable: Union[NoneType, bool]
    are_alcohol_sales_restricted: bool
    alcohol_sale_restricted_sun_start: Union[NoneType, str]
    alcohol_sale_restricted_sun_end: Union[NoneType, str]
    alcohol_sale_restricted_mon_start: Union[NoneType, str]
    alcohol_sale_restricted_mon_end: Union[NoneType, str]
    alcohol_sale_restricted_tue_start: Union[NoneType, str]
    alcohol_sale_restricted_tue_end: Union[NoneType, str]
    alcohol_sale_restricted_wed_start: Union[NoneType, str]
    alcohol_sale_restricted_wed_end: Union[NoneType, str]
    alcohol_sale_restricted_thu_start: Union[NoneType, str]
    alcohol_sale_restricted_thu_end: Union[NoneType, str]
    alcohol_sale_restricted_fri_start: Union[NoneType, str]
    alcohol_sale_restricted_fri_end: Union[NoneType, str]
    alcohol_sale_restricted_sat_start: Union[NoneType, str]
    alcohol_sale_restricted_sat_end: Union[NoneType, str]
    alcohol_banned_zip_codes: None
    mfuel_flag: bool
    comment_info: None
    dlvry_order_weekday_open: str
    dlvry_order_weekday_close: str
    dlvry_order_sat_open: str
    dlvry_order_sat_close: str
    dlvry_order_sun_open: str
    dlvry_order_sun_close: str

    # Internal fields
    _meijer_client: Optional["MeijerComprehensiveClient"] = field(default=None, repr=False)
    _raw_data: Optional[Dict[str, Any]] = field(default=None, repr=False)

    @classmethod
    def from_store_info_response(cls, store_data: Dict[str, Any], client: Optional["MeijerComprehensiveClient"] = None) -> "MeijerStore":
        """
        Create a MeijerStore from storeInfo API response data.
        
        Args:
            store_data: Raw store data from storeInfo API response
            client: Meijer client for additional operations
            
        Returns:
            MeijerStore instance
        """
        # Create instance with discovered field mappings
        kwargs = {
            '_meijer_client': client,
            '_raw_data': store_data
        }
        
        # Map storeInfo response fields to dataclass fields
        field_mappings = {
            'store_id': store_data.get('storeId'),
            'store_id': store_data.get('id'),
            'name': store_data.get('name'),
            'address': store_data.get('address'),
            'phone': store_data.get('phone'),
            'latitude': store_data.get('latitude'),
            'longitude': store_data.get('longitude'),
            'distance': store_data.get('distance'),
            'is_open': store_data.get('isOpen'),
            'store_hours': store_data.get('storeHours'),
        }
        
        # Apply direct field mappings
        for python_field, api_value in field_mappings.items():
            if hasattr(cls, python_field) and api_value is not None:
                kwargs[python_field] = api_value
        
        # Handle nested structures
        if 'address' in store_data and isinstance(store_data['address'], dict):
            address_data = store_data['address']
            kwargs.update({
                'address_line1': address_data.get('line1'),
                'address_line2': address_data.get('line2'),
                'address_city': address_data.get('city'),
                'address_state': address_data.get('state'),
                'address_zipcode': address_data.get('zipCode'),
                'address_country': address_data.get('country')
            })
        
        return cls(**{k: v for k, v in kwargs.items() if hasattr(cls, k) and v is not None})
    
    @property
    def store_id(self) -> str:
        """Get the store ID."""
        return getattr(self, 'id', '') or getattr(self, 'storeid', '') or getattr(self, 'store_id', '')
    
    @property
    def display_name(self) -> str:
        """Get the store display name."""
        return getattr(self, 'name', '') or f"Meijer Store {self.store_id}"
    
    @property
    def full_address(self) -> str:
        """Get the complete formatted address."""
        address_parts = []
        
        if hasattr(self, 'address_line1') and self.address_line1:
            address_parts.append(self.address_line1)
        if hasattr(self, 'address_line2') and self.address_line2:
            address_parts.append(self.address_line2)
        
        city_state_zip = []
        if hasattr(self, 'address_city') and self.address_city:
            city_state_zip.append(self.address_city)
        if hasattr(self, 'address_state') and self.address_state:
            city_state_zip.append(self.address_state)
        if hasattr(self, 'address_zipcode') and self.address_zipcode:
            city_state_zip.append(str(self.address_zipcode))
        
        if city_state_zip:
            address_parts.append(', '.join(city_state_zip))
        
        return ', '.join(address_parts) if address_parts else 'Address not available'
    
    @property
    def coordinates(self) -> Optional[Dict[str, float]]:
        """Get store coordinates."""
        lat = getattr(self, 'latitude', None)
        lng = getattr(self, 'longitude', None)
        
        if lat is not None and lng is not None:
            return {'latitude': float(lat), 'longitude': float(lng)}
        return None
    
    @property
    def distance_miles(self) -> Optional[float]:
        """Get distance in miles (if from proximity search)."""
        distance = getattr(self, 'distance', None)
        if distance is not None:
            try:
                return float(distance)
            except (ValueError, TypeError):
                pass
        return None
    
    def is_open_now(self) -> bool:
        """Check if store is currently open."""
        is_open = getattr(self, 'is_open', None)
        if is_open is not None:
            return bool(is_open)
        
        # Could implement store hours checking logic here
        return True  # Default assumption
    
    def get_store_hours(self) -> Dict[str, Any]:
        """Get store hours information."""
        hours = getattr(self, 'store_hours', None)
        if hours:
            return hours if isinstance(hours, dict) else {}
        
        return {}
    
    def get_store_services(self) -> List[str]:
        """Get list of store services."""
        services = []
        
        # Check for common service flags discovered in analysis
        service_fields = [
            ('pharmacy', 'Pharmacy'),
            ('gas_station', 'Gas Station'),
            ('grocery_pickup', 'Grocery Pickup'),
            ('home_delivery', 'Home Delivery'),
            ('liquor', 'Liquor Store')
        ]
        
        for field_name, service_name in service_fields:
            if hasattr(self, field_name) and getattr(self, field_name):
                services.append(service_name)
        
        return services
    
    def get_contact_info(self) -> Dict[str, str]:
        """Get store contact information."""
        contact = {}
        
        if hasattr(self, 'phone') and self.phone:
            contact['phone'] = self.phone
        
        contact['address'] = self.full_address
        
        if self.coordinates:
            contact['coordinates'] = f"{self.coordinates['latitude']}, {self.coordinates['longitude']}"
        
        return contact
    
    def calculate_distance_to(self, latitude: float, longitude: float) -> Optional[float]:
        """
        Calculate distance to given coordinates (if store coordinates are available).
        
        Args:
            latitude: Target latitude
            longitude: Target longitude
            
        Returns:
            Distance in miles, or None if store coordinates not available
        """
        if not self.coordinates:
            return None
        
        # Simple distance calculation (Haversine formula would be more accurate)
        import math
        
        store_lat = math.radians(self.coordinates['latitude'])
        store_lng = math.radians(self.coordinates['longitude'])
        target_lat = math.radians(latitude)
        target_lng = math.radians(longitude)
        
        dlat = target_lat - store_lat
        dlng = target_lng - store_lng
        
        a = math.sin(dlat/2)**2 + math.cos(store_lat) * math.cos(target_lat) * math.sin(dlng/2)**2
        c = 2 * math.asin(math.sqrt(a))
        
        # Earth's radius in miles
        radius_miles = 3956
        
        return c * radius_miles
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert store to dictionary representation."""
        result = {}
        for field_name, field_value in self.__dict__.items():
            if field_name.startswith('_'):
                continue
            result[field_name] = field_value
        return result
    
    def __str__(self) -> str:
        """String representation of the store."""
        distance_str = f" ({self.distance_miles:.1f} mi)" if self.distance_miles else ""
        return f"MeijerStore({self.display_name}{distance_str}) - {self.full_address}"
    
    def __repr__(self) -> str:
        """Detailed representation of the store."""
        return f"MeijerStore(id={self.store_id}, name='{self.display_name}', coordinates={self.coordinates})"


# Factory function for creating MeijerStore lists from storeInfo responses
def create_meijer_stores_from_response(response_data: Dict[str, Any], client: Optional["MeijerComprehensiveClient"] = None) -> List[MeijerStore]:
    """
    Create a list of MeijerStore objects from storeInfo API response.
    
    Args:
        response_data: Response from storeInfo API
        client: Meijer client for additional operations
        
    Returns:
        List of MeijerStore objects
    """
    stores = []
    
    # Handle different storeInfo response structures
    store_data_list = []
    
    if isinstance(response_data, dict):
        if 'stores' in response_data:
            store_data_list = response_data['stores']
        elif 'data' in response_data:
            data = response_data['data']
            if isinstance(data, dict) and 'stores' in data:
                store_data_list = data['stores']
            elif isinstance(data, list):
                store_data_list = data
        elif 'storeId' in response_data or 'id' in response_data:
            # Single store response
            store_data_list = [response_data]
    elif isinstance(response_data, list):
        store_data_list = response_data
    
    for store_data in store_data_list:
        try:
            store = MeijerStore.from_store_info_response(store_data, client)
            stores.append(store)
        except Exception as e:
            logger.error(f"Failed to create MeijerStore from data: {e}")
            continue
    
    return stores


if __name__ == "__main__":
    print("MeijerStore class generated from storeInfo API analysis")
    print(f"Based on analysis of storeInfo endpoints")
