#!/usr/bin/env python3
"""
MeijerStore class generated from storeInfo API analysis.

This class represents Meijer store information returned from storeInfo endpoints
and includes all discovered fields from the API responses.

Generated by analyzing meijer2.log storeInfo endpoints.
Generated by: Claude Sonnet 4 (claude-3-5-sonnet-20241022) 
via Cursor IDE (cursor.sh) with AI assistance
"""

from typing import Optional, Union, List, Dict, Any, TYPE_CHECKING
from dataclasses import dataclass, field
from datetime import datetime
import json
import logging
import math

if TYPE_CHECKING:
    from meijer_comprehensive import MeijerComprehensiveClient

logger = logging.getLogger(__name__)


@dataclass
class MeijerStore:
    """
    Represents a Meijer store from storeInfo API results.
    
    This class contains all fields discovered from storeInfo API analysis
    and provides methods for interacting with store information.
    
    Based on analysis of 634 stores with 190 unique fields.
    """
    
    # Core identification and location
    unit_id: int  # Store ID (primary identifier)
    name: str  # Store name
    address: str  # Street address
    city: str  # City
    state: str  # State abbreviation  
    zip_code: str  # ZIP code
    phone_number: str  # Main phone number
    latitude: float  # Latitude coordinate
    longitude: float  # Longitude coordinate
    
    # Distance and search info
    distance: Optional[float] = None  # Distance from search point (miles)
    miles_from: Optional[float] = None  # Alternative distance field
    
    # Store details
    unit_type: Optional[str] = None  # Store type
    open_date: Optional[str] = None  # Store opening date
    timezone: Optional[str] = None  # Store timezone
    daylight_savings: Optional[bool] = None  # Daylight savings info
    
    # Store hours and services
    store_24hrs_flag: Optional[bool] = None  # 24-hour store flag
    store_weekday_open: Optional[str] = None  # Weekday opening time
    store_weekday_close: Optional[str] = None  # Weekday closing time
    store_sat_open: Optional[str] = None  # Saturday opening time
    store_sat_close: Optional[str] = None  # Saturday closing time
    store_sun_open: Optional[str] = None  # Sunday opening time
    store_sun_close: Optional[str] = None  # Sunday closing time
    store_hours: Optional[List[Dict[str, Any]]] = None  # Complete store hours
    
    # Pharmacy services
    pharm_daily_open: Optional[str] = None  # Pharmacy daily open
    pharm_daily_close: Optional[str] = None  # Pharmacy daily close
    pharm_sat_open: Optional[str] = None  # Pharmacy Saturday open
    pharm_sat_close: Optional[str] = None  # Pharmacy Saturday close
    pharm_sun_open: Optional[str] = None  # Pharmacy Sunday open
    pharm_sun_close: Optional[str] = None  # Pharmacy Sunday close
    pharm_holiday_open: Optional[str] = None  # Pharmacy holiday hours
    pharm_holiday_close: Optional[str] = None  # Pharmacy holiday hours
    pharm_address: Optional[str] = None  # Pharmacy address
    pharm_phone: Optional[str] = None  # Pharmacy phone
    pharm_timezone: Optional[str] = None  # Pharmacy timezone
    drive_thru: Optional[bool] = None  # Drive-thru availability
    clinic: Optional[bool] = None  # Clinic availability
    
    # Pickup and delivery services
    is_mobile_shopping_enabled: Optional[bool] = None  # Mobile shopping
    is_mobile_payment_enabled: Optional[bool] = None  # Mobile payment
    curbside_allow: Optional[bool] = None  # Curbside pickup allowed
    curbside_phone: Optional[str] = None  # Curbside phone
    curbside_drive_thru: Optional[bool] = None  # Curbside drive-thru
    curbside_weekday_open: Optional[str] = None  # Curbside weekday hours
    curbside_weekday_close: Optional[str] = None
    curbside_sat_open: Optional[str] = None  # Curbside Saturday hours
    curbside_sat_close: Optional[str] = None
    curbside_sun_open: Optional[str] = None  # Curbside Sunday hours
    curbside_sun_close: Optional[str] = None
    curbside_holiday_open: Optional[str] = None  # Curbside holiday hours
    curbside_holiday_close: Optional[str] = None
    curbside_instore_allow: Optional[bool] = None  # In-store curbside
    
    # Pre-order services
    pre_order_service_allow: Optional[bool] = None  # Pre-order allowed
    pre_order_phone: Optional[str] = None  # Pre-order phone
    pre_order_drive_thru: Optional[bool] = None  # Pre-order drive-thru
    pre_order_instore_allow: Optional[bool] = None  # In-store pre-order
    pre_order_weekday_open: Optional[str] = None  # Pre-order hours
    pre_order_weekday_close: Optional[str] = None
    pre_order_sat_open: Optional[str] = None
    pre_order_sat_close: Optional[str] = None
    pre_order_sun_open: Optional[str] = None
    pre_order_sun_close: Optional[str] = None
    pre_order_holiday_open: Optional[str] = None
    pre_order_holiday_close: Optional[str] = None
    
    # Delivery services
    dlvry_order_service_allow: Optional[bool] = None  # Delivery allowed
    dlvry_order_phone: Optional[str] = None  # Delivery phone
    dlvry_description: Optional[str] = None  # Delivery description
    dlvry_order_weekday_open: Optional[str] = None  # Delivery hours
    dlvry_order_weekday_close: Optional[str] = None
    dlvry_order_sat_open: Optional[str] = None
    dlvry_order_sat_close: Optional[str] = None
    dlvry_order_sun_open: Optional[str] = None
    dlvry_order_sun_close: Optional[str] = None
    dlvry_order_holiday_open: Optional[str] = None
    dlvry_order_holiday_close: Optional[str] = None
    
    # Deli services
    deli_order_service_allow: Optional[bool] = None  # Deli ordering
    deli_order_phone: Optional[str] = None  # Deli phone
    deli_description: Optional[str] = None  # Deli description
    deli_order_weekday_open: Optional[str] = None  # Deli hours
    deli_order_weekday_close: Optional[str] = None
    deli_order_sat_open: Optional[str] = None
    deli_order_sat_close: Optional[str] = None
    deli_order_sun_open: Optional[str] = None
    deli_order_sun_close: Optional[str] = None
    deli_order_holiday_open: Optional[str] = None
    deli_order_holiday_close: Optional[str] = None
    
    # Alcohol services
    is_alcohol_pickupable: Optional[bool] = None  # Alcohol pickup
    is_alcohol_deliverable: Optional[bool] = None  # Alcohol delivery
    are_alcohol_sales_restricted: Optional[bool] = None  # Alcohol restrictions
    alcohol_sale_restricted_sun_start: Optional[str] = None  # Sunday restrictions
    alcohol_sale_restricted_sun_end: Optional[str] = None
    alcohol_sale_restricted_mon_start: Optional[str] = None  # Monday restrictions
    alcohol_sale_restricted_mon_end: Optional[str] = None
    alcohol_sale_restricted_tue_start: Optional[str] = None  # Tuesday restrictions
    alcohol_sale_restricted_tue_end: Optional[str] = None
    alcohol_sale_restricted_wed_start: Optional[str] = None  # Wednesday restrictions
    alcohol_sale_restricted_wed_end: Optional[str] = None
    alcohol_sale_restricted_thu_start: Optional[str] = None  # Thursday restrictions
    alcohol_sale_restricted_thu_end: Optional[str] = None
    alcohol_sale_restricted_fri_start: Optional[str] = None  # Friday restrictions
    alcohol_sale_restricted_fri_end: Optional[str] = None
    alcohol_sale_restricted_sat_start: Optional[str] = None  # Saturday restrictions
    alcohol_sale_restricted_sat_end: Optional[str] = None
    alcohol_banned_zip_codes: Optional[List[str]] = None  # Banned ZIP codes
    
    # Gas station services
    mfuel_flag: Optional[bool] = None  # Gas station flag
    gas_station_amenities: Optional[List[Dict[str, Any]]] = None  # Gas amenities
    gas_station_hours: Optional[Dict[str, Any]] = None  # Gas station hours
    fuel_prices: Optional[Dict[str, Any]] = None  # Fuel prices
    
    # Management and staff
    store_dir_name: Optional[str] = None  # Store director name
    store_dir_emp_id: Optional[str] = None  # Store director employee ID
    
    # Technical and system info
    market_and_region: Optional[Dict[str, Any]] = None  # Market/region info
    fulfillment_info: Optional[List[Dict[str, Any]]] = None  # Fulfillment info
    aux_unit_info: Optional[List[Dict[str, Any]]] = None  # Auxiliary unit info
    tenants: Optional[List[Dict[str, Any]]] = None  # Store tenants
    mfc_unit_id: Optional[str] = None  # MFC unit ID
    mfc_phone_number: Optional[str] = None  # MFC phone
    aurus_merchant_id: Optional[str] = None  # Payment system ID
    aurus_terminal_id: Optional[str] = None  # Payment terminal ID
    
    # Flags and settings
    store_flag: Optional[str] = None  # Store flag
    visible_date: Optional[str] = None  # Visibility date
    cnc_pickup_description: Optional[str] = None  # Click & collect description
    spo_pickup_description: Optional[str] = None  # Special pickup description
    comment_info: Optional[str] = None  # Comment information
    holiday_info: Optional[Dict[str, Any]] = None  # Holiday information
    
    # Internal fields
    _meijer_client: Optional["MeijerComprehensiveClient"] = field(default=None, repr=False)
    _raw_data: Optional[Dict[str, Any]] = field(default=None, repr=False)
    
    @classmethod
    def from_store_info_response(cls, store_data: Dict[str, Any], client: Optional["MeijerComprehensiveClient"] = None) -> "MeijerStore":
        """
        Create a MeijerStore from storeInfo API response data.
        
        Args:
            store_data: Raw store data from storeInfo API response
            client: Meijer client for additional operations
            
        Returns:
            MeijerStore instance
        """
        # Extract and convert data with proper field mappings
        kwargs = {
            '_meijer_client': client,
            '_raw_data': store_data,
            
            # Core identification (required fields)
            'unit_id': store_data.get('UnitId', 0),
            'name': store_data.get('Name', ''),
            'address': store_data.get('Address', ''),
            'city': store_data.get('City', ''),
            'state': store_data.get('State', ''),
            'zip_code': store_data.get('Zip', ''),
            'phone_number': store_data.get('PhoneNumber', ''),
            'latitude': float(store_data.get('Latitude', 0.0)),
            'longitude': float(store_data.get('Longitude', 0.0)),
            
            # Distance info
            'distance': store_data.get('Distance') or store_data.get('MilesFrom'),
            'miles_from': store_data.get('MilesFrom'),
            
            # Store details
            'unit_type': store_data.get('UnitType'),
            'open_date': store_data.get('OpenDate'),
            'timezone': store_data.get('TimeZone'),
            'daylight_savings': store_data.get('DaylightSavings'),
            
            # Store hours
            'store_24hrs_flag': store_data.get('Store24HrsFlag'),
            'store_weekday_open': store_data.get('StoreWeekdayOpen'),
            'store_weekday_close': store_data.get('StoreWeekdayClose'),
            'store_sat_open': store_data.get('StoreSatOpen'),
            'store_sat_close': store_data.get('StoreSatClose'),
            'store_sun_open': store_data.get('StoreSunOpen'),
            'store_sun_close': store_data.get('StoreSunClose'),
            'store_hours': store_data.get('StoreHours'),
            
            # Pharmacy
            'pharm_daily_open': store_data.get('PharmDailyOpen'),
            'pharm_daily_close': store_data.get('PharmDailyClose'),
            'pharm_sat_open': store_data.get('PharmSatOpen'),
            'pharm_sat_close': store_data.get('PharmSatClose'),
            'pharm_sun_open': store_data.get('PharmSunOpen'),
            'pharm_sun_close': store_data.get('PharmSunClose'),
            'pharm_holiday_open': store_data.get('PharmHolidayOpen'),
            'pharm_holiday_close': store_data.get('PharmHolidayClose'),
            'pharm_address': store_data.get('PharmAddress'),
            'pharm_phone': store_data.get('PharmPhone'),
            'pharm_timezone': store_data.get('PharmTimezone'),
            'drive_thru': store_data.get('DriveThru'),
            'clinic': store_data.get('Clinic'),
            
            # Mobile and pickup services
            'is_mobile_shopping_enabled': store_data.get('IsMobileShoppingEnabled'),
            'is_mobile_payment_enabled': store_data.get('IsMobilePaymentEnabled'),
            'curbside_allow': cls._convert_bool(store_data.get('CurbsideAllow')),
            'curbside_phone': store_data.get('CurbsidePhone'),
            'curbside_drive_thru': cls._convert_bool(store_data.get('CurbsideDriveThru')),
            'curbside_weekday_open': store_data.get('CurbsideWeekdayOpen'),
            'curbside_weekday_close': store_data.get('CurbsideWeekdayClose'),
            'curbside_sat_open': store_data.get('CurbsideSatOpen'),
            'curbside_sat_close': store_data.get('CurbsideSatClose'),
            'curbside_sun_open': store_data.get('CurbsideSunOpen'),
            'curbside_sun_close': store_data.get('CurbsideSunClose'),
            'curbside_holiday_open': store_data.get('CurbsideHolidayOpen'),
            'curbside_holiday_close': store_data.get('CurbsideHolidayClose'),
            'curbside_instore_allow': cls._convert_bool(store_data.get('CurbsideInstoreAllow')),
            
            # Pre-order services
            'pre_order_service_allow': cls._convert_bool(store_data.get('PreOrderServiceAllow')),
            'pre_order_phone': store_data.get('PreOrderPhone'),
            'pre_order_drive_thru': cls._convert_bool(store_data.get('PreOrderDriveThru')),
            'pre_order_instore_allow': cls._convert_bool(store_data.get('PreOrderInstoreAllow')),
            'pre_order_weekday_open': store_data.get('PreOrderWeekdayOpen'),
            'pre_order_weekday_close': store_data.get('PreOrderWeekdayClose'),
            'pre_order_sat_open': store_data.get('PreOrderSatOpen'),
            'pre_order_sat_close': store_data.get('PreOrderSatClose'),
            'pre_order_sun_open': store_data.get('PreOrderSunOpen'),
            'pre_order_sun_close': store_data.get('PreOrderSunClose'),
            'pre_order_holiday_open': store_data.get('PreOrderHolidayOpen'),
            'pre_order_holiday_close': store_data.get('PreOrderHolidayClose'),
            
            # Delivery services
            'dlvry_order_service_allow': cls._convert_bool(store_data.get('DlvryOrderServiceAllow')),
            'dlvry_order_phone': store_data.get('DlvryOrderPhone'),
            'dlvry_description': store_data.get('DlvryDescription'),
            'dlvry_order_weekday_open': store_data.get('DlvryOrderWeekdayOpen'),
            'dlvry_order_weekday_close': store_data.get('DlvryOrderWeekdayClose'),
            'dlvry_order_sat_open': store_data.get('DlvryOrderSatOpen'),
            'dlvry_order_sat_close': store_data.get('DlvryOrderSatClose'),
            'dlvry_order_sun_open': store_data.get('DlvryOrderSunOpen'),
            'dlvry_order_sun_close': store_data.get('DlvryOrderSunClose'),
            'dlvry_order_holiday_open': store_data.get('DlvryOrderHolidayOpen'),
            'dlvry_order_holiday_close': store_data.get('DlvryOrderHolidayClose'),
            
            # Deli services
            'deli_order_service_allow': cls._convert_bool(store_data.get('DeliOrderServiceAllow')),
            'deli_order_phone': store_data.get('DeliOrderPhone'),
            'deli_description': store_data.get('DeliDescription'),
            'deli_order_weekday_open': store_data.get('DeliOrderWeekdayOpen'),
            'deli_order_weekday_close': store_data.get('DeliOrderWeekdayClose'),
            'deli_order_sat_open': store_data.get('DeliOrderSatOpen'),
            'deli_order_sat_close': store_data.get('DeliOrderSatClose'),
            'deli_order_sun_open': store_data.get('DeliOrderSunOpen'),
            'deli_order_sun_close': store_data.get('DeliOrderSunClose'),
            'deli_order_holiday_open': store_data.get('DeliOrderHolidayOpen'),
            'deli_order_holiday_close': store_data.get('DeliOrderHolidayClose'),
            
            # Alcohol services
            'is_alcohol_pickupable': store_data.get('IsAlcoholPickupable'),
            'is_alcohol_deliverable': store_data.get('IsAlcoholDeliverable'),
            'are_alcohol_sales_restricted': store_data.get('AreAlcoholSalesRestricted'),
            'alcohol_sale_restricted_sun_start': store_data.get('AlcoholSaleRestrictedSunStart'),
            'alcohol_sale_restricted_sun_end': store_data.get('AlcoholSaleRestrictedSunEnd'),
            'alcohol_sale_restricted_mon_start': store_data.get('AlcoholSaleRestrictedMonStart'),
            'alcohol_sale_restricted_mon_end': store_data.get('AlcoholSaleRestrictedMonEnd'),
            'alcohol_sale_restricted_tue_start': store_data.get('AlcoholSaleRestrictedTueStart'),
            'alcohol_sale_restricted_tue_end': store_data.get('AlcoholSaleRestrictedTueEnd'),
            'alcohol_sale_restricted_wed_start': store_data.get('AlcoholSaleRestrictedWedStart'),
            'alcohol_sale_restricted_wed_end': store_data.get('AlcoholSaleRestrictedWedEnd'),
            'alcohol_sale_restricted_thu_start': store_data.get('AlcoholSaleRestrictedThuStart'),
            'alcohol_sale_restricted_thu_end': store_data.get('AlcoholSaleRestrictedThuEnd'),
            'alcohol_sale_restricted_fri_start': store_data.get('AlcoholSaleRestrictedFriStart'),
            'alcohol_sale_restricted_fri_end': store_data.get('AlcoholSaleRestrictedFriEnd'),
            'alcohol_sale_restricted_sat_start': store_data.get('AlcoholSaleRestrictedSatStart'),
            'alcohol_sale_restricted_sat_end': store_data.get('AlcoholSaleRestrictedSatEnd'),
            'alcohol_banned_zip_codes': store_data.get('AlcoholBannedZipCodes'),
            
            # Gas station
            'mfuel_flag': store_data.get('MfuelFlag'),
            'gas_station_amenities': store_data.get('GasStationAmenities'),
            'gas_station_hours': store_data.get('GasStationHours'),
            'fuel_prices': store_data.get('FuelPrices'),
            
            # Management
            'store_dir_name': store_data.get('StoreDirName'),
            'store_dir_emp_id': store_data.get('StoreDirEmpId'),
            
            # System info
            'market_and_region': store_data.get('MarketAndRegion'),
            'fulfillment_info': store_data.get('FulfillmentInfo'),
            'aux_unit_info': store_data.get('AuxUnitInfo'),
            'tenants': store_data.get('Tenants'),
            'mfc_unit_id': store_data.get('MfcUnitId'),
            'mfc_phone_number': store_data.get('MfcPhoneNumber'),
            'aurus_merchant_id': store_data.get('AurusMerchantId'),
            'aurus_terminal_id': store_data.get('AurusTerminalId'),
            
            # Other info
            'store_flag': store_data.get('StoreFlag'),
            'visible_date': store_data.get('VisibleDate'),
            'cnc_pickup_description': store_data.get('CNCPickupDescription'),
            'spo_pickup_description': store_data.get('SPOPickupDescription'),
            'comment_info': store_data.get('CommentInfo'),
            'holiday_info': store_data.get('HolidayInfo'),
        }
        
        # Filter out None values for optional fields
        filtered_kwargs = {}
        for k, v in kwargs.items():
            if k in ['unit_id', 'name', 'address', 'city', 'state', 'zip_code', 'phone_number', 'latitude', 'longitude', '_meijer_client', '_raw_data']:
                # Always include required fields and internal fields
                filtered_kwargs[k] = v
            elif v is not None:
                # Only include optional fields if they have values
                filtered_kwargs[k] = v
        
        return cls(**filtered_kwargs)
    
    @staticmethod
    def _convert_bool(value: Any) -> Optional[bool]:
        """Convert various string/value representations to boolean."""
        if value is None or value == '':
            return None
        if isinstance(value, bool):
            return value
        if isinstance(value, str):
            return value.lower() in ('true', 'yes', '1', 'y')
        return bool(value)
    
    @property
    def store_id(self) -> int:
        """Get the store ID as integer."""
        return self.unit_id
    
    @property
    def display_name(self) -> str:
        """Get the store display name."""
        if self.name:
            return f"Meijer {self.name}"
        return f"Meijer Store {self.unit_id}"
    
    @property
    def full_address(self) -> str:
        """Get the complete formatted address."""
        parts = [self.address]
        
        city_state_zip = []
        if self.city:
            city_state_zip.append(self.city)
        if self.state:
            city_state_zip.append(self.state)
        if self.zip_code:
            city_state_zip.append(self.zip_code)
        
        if city_state_zip:
            parts.append(', '.join(city_state_zip))
        
        return ', '.join(parts)
    
    @property
    def coordinates(self) -> Dict[str, float]:
        """Get store coordinates."""
        return {'latitude': self.latitude, 'longitude': self.longitude}
    
    @property
    def distance_miles(self) -> Optional[float]:
        """Get distance in miles (if from proximity search)."""
        return self.distance or self.miles_from
    
    def has_pharmacy(self) -> bool:
        """Check if store has a pharmacy."""
        return bool(self.pharm_phone or self.pharm_address or 
                   self.pharm_daily_open or self.pharm_daily_close)
    
    def has_gas_station(self) -> bool:
        """Check if store has a gas station."""
        return bool(self.mfuel_flag)
    
    def has_curbside_pickup(self) -> bool:
        """Check if store offers curbside pickup."""
        return bool(self.curbside_allow)
    
    def has_delivery(self) -> bool:
        """Check if store offers delivery."""
        return bool(self.dlvry_order_service_allow)
    
    def has_alcohol_sales(self) -> bool:
        """Check if store sells alcohol."""
        return bool(self.is_alcohol_pickupable or self.is_alcohol_deliverable)
    
    def is_24_hours(self) -> bool:
        """Check if store is open 24 hours."""
        return bool(self.store_24hrs_flag)
    
    def get_store_services(self) -> List[str]:
        """Get list of store services."""
        services = []
        
        if self.has_pharmacy():
            services.append('Pharmacy')
        if self.has_gas_station():
            services.append('Gas Station')
        if self.has_curbside_pickup():
            services.append('Curbside Pickup')
        if self.has_delivery():
            services.append('Home Delivery')
        if self.has_alcohol_sales():
            services.append('Alcohol Sales')
        if self.is_24_hours():
            services.append('24 Hours')
        if self.clinic:
            services.append('Clinic')
        if self.drive_thru:
            services.append('Drive-Thru')
        if self.deli_order_service_allow:
            services.append('Deli Orders')
        if self.pre_order_service_allow:
            services.append('Pre-Orders')
        
        return services
    
    def get_contact_info(self) -> Dict[str, str]:
        """Get store contact information."""
        contact = {
            'phone': self.phone_number,
            'address': self.full_address,
            'coordinates': f"{self.latitude}, {self.longitude}"
        }
        
        if self.pharm_phone:
            contact['pharmacy_phone'] = self.pharm_phone
        if self.curbside_phone:
            contact['curbside_phone'] = self.curbside_phone
        if self.pre_order_phone:
            contact['preorder_phone'] = self.pre_order_phone
        if self.dlvry_order_phone:
            contact['delivery_phone'] = self.dlvry_order_phone
        if self.deli_order_phone:
            contact['deli_phone'] = self.deli_order_phone
        
        return contact
    
    def get_hours_summary(self) -> Dict[str, str]:
        """Get store hours summary."""
        hours = {}
        
        if self.is_24_hours():
            hours['store'] = '24 Hours'
        else:
            if self.store_weekday_open and self.store_weekday_close:
                hours['weekdays'] = f"{self.store_weekday_open} - {self.store_weekday_close}"
            if self.store_sat_open and self.store_sat_close:
                hours['saturday'] = f"{self.store_sat_open} - {self.store_sat_close}"
            if self.store_sun_open and self.store_sun_close:
                hours['sunday'] = f"{self.store_sun_open} - {self.store_sun_close}"
        
        if self.pharm_daily_open and self.pharm_daily_close:
            hours['pharmacy'] = f"{self.pharm_daily_open} - {self.pharm_daily_close}"
        
        return hours
    
    def calculate_distance_to(self, latitude: float, longitude: float) -> float:
        """
        Calculate distance to given coordinates using Haversine formula.
        
        Args:
            latitude: Target latitude
            longitude: Target longitude
            
        Returns:
            Distance in miles
        """
        # Haversine formula
        R = 3959  # Earth's radius in miles
        
        lat1_rad = math.radians(self.latitude)
        lon1_rad = math.radians(self.longitude)
        lat2_rad = math.radians(latitude)
        lon2_rad = math.radians(longitude)
        
        dlat = lat2_rad - lat1_rad
        dlon = lon2_rad - lon1_rad
        
        a = (math.sin(dlat/2)**2 + 
             math.cos(lat1_rad) * math.cos(lat2_rad) * math.sin(dlon/2)**2)
        c = 2 * math.asin(math.sqrt(a))
        
        return R * c
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert store to dictionary representation."""
        result = {}
        for field_name, field_value in self.__dict__.items():
            if field_name.startswith('_'):
                continue
            result[field_name] = field_value
        return result
    
    def __str__(self) -> str:
        """String representation of the store."""
        distance_str = f" ({self.distance_miles:.1f} mi)" if self.distance_miles else ""
        services = ", ".join(self.get_store_services()[:3])  # Show first 3 services
        services_str = f" - {services}" if services else ""
        return f"MeijerStore({self.display_name}{distance_str}){services_str}"
    
    def __repr__(self) -> str:
        """Detailed representation of the store."""
        return f"MeijerStore(id={self.unit_id}, name='{self.name}', city='{self.city}', state='{self.state}')"


# Factory function for creating MeijerStore lists from storeInfo responses
def create_meijer_stores_from_response(response_data: Dict[str, Any], client: Optional["MeijerComprehensiveClient"] = None) -> List[MeijerStore]:
    """
    Create a list of MeijerStore objects from storeInfo API response.
    
    Args:
        response_data: Response from storeInfo API
        client: Meijer client for additional operations
        
    Returns:
        List of MeijerStore objects
    """
    stores = []
    
    # Handle different storeInfo response structures
    store_data_list = []
    
    if isinstance(response_data, dict):
        if 'store' in response_data:  # Meijer uses 'store' not 'stores'
            store_data_list = response_data['store']
        elif 'stores' in response_data:
            store_data_list = response_data['stores']
        elif 'data' in response_data:
            data = response_data['data']
            if isinstance(data, dict) and 'stores' in data:
                store_data_list = data['stores']
            elif isinstance(data, dict) and 'store' in data:
                store_data_list = data['store']
            elif isinstance(data, list):
                store_data_list = data
        elif 'UnitId' in response_data:  # Single store response
            store_data_list = [response_data]
    elif isinstance(response_data, list):
        store_data_list = response_data
    
    for store_data in store_data_list:
        try:
            store = MeijerStore.from_store_info_response(store_data, client)
            stores.append(store)
        except Exception as e:
            logger.error(f"Failed to create MeijerStore from data: {e}")
            continue
    
    return stores


if __name__ == "__main__":
    print("MeijerStore class generated from storeInfo API analysis")
    print("Based on analysis of 634 stores with 190 unique fields")
    print("Core store identification: UnitId (store ID)")
    print("Key services: Pharmacy, Gas Station, Curbside, Delivery, Alcohol") 