#!/usr/bin/env python3
"""
MeijerItem class generated from Constructor.io search API analysis.

This class represents items returned from Meijer's search backend (Constructor.io)
and includes all discovered fields from the search API responses.

Generated by analyzing meijer2.log Constructor.io endpoints.
"""

from typing import Optional, Union, List, Dict, Any, TYPE_CHECKING
from dataclasses import dataclass, field
from datetime import datetime
import json
import logging

if TYPE_CHECKING:
    from meijer_comprehensive import MeijerComprehensiveClient

logger = logging.getLogger(__name__)


@dataclass
class MeijerItem:
    """
    Represents a Meijer product item from search results.
    
    This class contains all fields discovered from Constructor.io API analysis
    and provides methods for interacting with individual items.
    """
    
    data_id: str
    data_ean: int
    data_isbopas: bool
    data_isbuyable: bool
    data_isalcohol: bool
    data_image_url: str
    data_priceunit: str
    data_hasmperks: bool
    data_specialbuy: bool
    data_description: str
    data_deactivated: bool
    data_productunit: str
    data_qtyincrement: int
    data_chokinghazard: bool
    data_ispurchasable: bool
    data_pricebyweight: bool
    data_mperksofferid: List[Any]
    data_isagerestricted: bool
    data_ebtfoodstampable: bool
    data_pickupavailableflag: bool
    data_homedeliverynotavailable: bool
    data_requiresdiscreteinventorytracking: bool
    data_sale: bool
    data_ismap: bool
    data_price: float
    data_variation_id: str
    data_pricegoodthrough: str
    data_stocklevelstatus: str
    data_discountsalepricevalue: Union[float, int]
    value: str
    data_group_ids: List[Any]
    data_ingredients: Optional[str] = None
    data_discountvalue: Optional[float] = None
    data_discountsavingstext: Optional[str] = None
    data_discountsalepricetype: Optional[str] = None
    data_depositvalue: Optional[float] = None
    data_maxorderquantity: Optional[int] = None
    data_discountsalepricetext: Optional[str] = None
    data_packagesize: Optional[str] = None
    matched_terms: List[Any]

    # Aisle location fields for defragging
    aisle_primary: Optional[str] = None
    aisle_locations: List[str] = field(default_factory=list)

    # Internal fields
    _meijer_client: Optional["MeijerComprehensiveClient"] = field(default=None, repr=False)
    _raw_data: Optional[Dict[str, Any]] = field(default=None, repr=False)

    @classmethod
    def from_constructor_response(cls, item_data: Dict[str, Any], client: Optional["MeijerComprehensiveClient"] = None) -> "MeijerItem":
        """
        Create a MeijerItem from Constructor.io API response data.
        
        Args:
            item_data: Raw item data from Constructor.io search response
            client: Meijer client for additional operations
            
        Returns:
            MeijerItem instance
        """
        # Extract common Constructor.io fields
        value = item_data.get('value', '')
        data = item_data.get('data', {})
        
        # Create instance with discovered field mappings
        kwargs = {
            '_meijer_client': client,
            '_raw_data': item_data
        }
        
        # Map common fields
        field_mappings = {
            'title': item_data.get('value'),
            'product_id': item_data.get('data_id'),
            'price': item_data.get('data_price'),
            'image_url': item_data.get('data_image_url'),
            'description': item_data.get('data_description'),
            'brand': item_data.get('data_brand'),
            'product_url': item_data.get('data_url'),
        }
        
        # Apply field mappings
        for field_name, value in field_mappings.items():
            if hasattr(cls, field_name):
                kwargs[field_name] = value
        
        return cls(**{k: v for k, v in kwargs.items() if v is not None})
    
    @property
    def title(self) -> str:
        """Get the item title/name."""
        return getattr(self, 'value', '') or getattr(self, 'title', '') or 'Unknown Item'
    
    @property
    def product_id(self) -> Optional[str]:
        """Get the product ID."""
        if hasattr(self, 'data_id'):
            return getattr(self, 'data_id', None)
        return getattr(self, 'id', None)
    
    @property
    def price(self) -> Optional[float]:
        """Get the item price."""
        price_val = getattr(self, 'data_price', None)
        if price_val:
            try:
                return float(price_val)
            except (ValueError, TypeError):
                pass
        return None
    
    @property
    def image_url(self) -> Optional[str]:
        """Get the item image URL."""
        return getattr(self, 'data_image_url', None)
    
    @property
    def brand(self) -> Optional[str]:
        """Get the item brand."""
        return getattr(self, 'data_brand', None)
    
    def add_to_cart(self, quantity: int = 1) -> bool:
        """
        Add this item to the shopping cart.
        
        Args:
            quantity: Number of items to add
            
        Returns:
            True if successful, False otherwise
        """
        if not self._meijer_client:
            logger.warning("No Meijer client associated with item")
            return False
        
        # This would need implementation in the Meijer client
        if hasattr(self._meijer_client, 'add_to_cart'):
            return self._meijer_client.add_to_cart(self.product_id, quantity)
        
        logger.warning("Meijer client does not support add_to_cart")
        return False
    
    def get_detailed_info(self) -> Dict[str, Any]:
        """
        Get detailed product information.
        
        Returns:
            Dictionary with detailed product data
        """
        if self._raw_data:
            return self._raw_data
        
        # Return basic info from current fields
        return {
            'title': self.title,
            'product_id': self.product_id,
            'price': self.price,
            'image_url': self.image_url,
            'brand': self.brand
        }
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert item to dictionary representation."""
        result = {}
        for field_name, field_value in self.__dict__.items():
            if field_name.startswith('_'):
                continue
            result[field_name] = field_value
        return result
    
    def __str__(self) -> str:
        """String representation of the item."""
        price_str = f"${self.price:.2f}" if self.price else "Price N/A"
        brand_str = f" by {self.brand}" if self.brand else ""
        return f"MeijerItem({self.title}{brand_str}) - {price_str}"
    
    def __repr__(self) -> str:
        """Detailed representation of the item."""
        return f"MeijerItem(id={self.product_id}, title='{self.title}', price={self.price})"


# Factory function for creating MeijerItem lists from search responses
def create_meijer_items_from_search(search_response: Dict[str, Any], client: Optional["MeijerComprehensiveClient"] = None) -> List[MeijerItem]:
    """
    Create a list of MeijerItem objects from Constructor.io search response.
    
    Args:
        search_response: Response from Constructor.io search API
        client: Meijer client for additional operations
        
    Returns:
        List of MeijerItem objects
    """
    items = []
    
    # Handle different Constructor.io response structures
    results = []
    if isinstance(search_response, dict):
        if 'results' in search_response:
            results = search_response['results']
        elif 'response' in search_response and isinstance(search_response['response'], dict):
            resp = search_response['response']
            if 'results' in resp:
                results = resp['results']
    
    for item_data in results:
        try:
            item = MeijerItem.from_constructor_response(item_data, client)
            items.append(item)
        except Exception as e:
            logger.error(f"Failed to create MeijerItem from data: {e}")
            continue
    
    return items


if __name__ == "__main__":
    print("MeijerItem class generated from Constructor.io API analysis")
    print(f"Based on analysis of Constructor.io search endpoints")
