#!/usr/bin/env python3
"""
MeijerItem class generated from Constructor.io search API analysis.

This class represents items returned from Meijer's search backend (Constructor.io)
and includes all discovered fields from the search API responses.

Generated by analyzing meijer2.log Constructor.io endpoints.
"""

from typing import Optional, Union, List, Dict, Any, TYPE_CHECKING
from dataclasses import dataclass, field
from datetime import datetime
import json
import logging

if TYPE_CHECKING:
    from meijer_comprehensive import MeijerComprehensiveClient

logger = logging.getLogger(__name__)


@dataclass
class MeijerItem:
    """
    Represents a Meijer product item from search results.
    
    This class contains all fields discovered from Constructor.io API analysis
    and provides methods for interacting with individual items.
    """
    
    data_id: str
    data_ean: int
    data_isbopas: bool
    data_isbuyable: bool
    data_isalcohol: bool
    data_image_url: str
    data_priceunit: str
    data_hasmperks: bool
    data_specialbuy: bool
    data_description: str
    data_deactivated: bool
    data_productunit: str
    data_qtyincrement: int
    data_chokinghazard: bool
    data_ispurchasable: bool
    data_pricebyweight: bool
    data_mperksofferid: List[Any]
    data_isagerestricted: bool
    data_ebtfoodstampable: bool
    data_pickupavailableflag: bool
    data_homedeliverynotavailable: bool
    data_requiresdiscreteinventorytracking: bool
    data_sale: bool
    data_ismap: bool
    data_price: float
    data_variation_id: str
    data_pricegoodthrough: str
    data_stocklevelstatus: str
    data_discountsalepricevalue: Union[float, int]
    value: str
    data_group_ids: List[Any]
    data_ingredients: Optional[str] = None
    data_discountvalue: Optional[float] = None
    data_discountsavingstext: Optional[str] = None
    data_discountsalepricetype: Optional[str] = None
    data_depositvalue: Optional[float] = None
    data_maxorderquantity: Optional[int] = None
    data_discountsalepricetext: Optional[str] = None
    data_packagesize: Optional[str] = None
    matched_terms: List[Any] = field(default_factory=list)

    # Aisle location fields for defragging
    aisle_primary: Optional[str] = None
    aisle_locations: List[str] = field(default_factory=list)

    # Internal fields
    _meijer_client: Optional["MeijerComprehensiveClient"] = field(default=None, repr=False)
    _raw_data: Optional[Dict[str, Any]] = field(default=None, repr=False)

    @classmethod
    def from_constructor_response(cls, item_data: Dict[str, Any], client: Optional["MeijerComprehensiveClient"] = None) -> "MeijerItem":
        """
        Create a MeijerItem from Constructor.io API response data.
        
        Args:
            item_data: Raw item data from Constructor.io search response
            client: Meijer client for additional operations
            
        Returns:
            MeijerItem instance
        """
        # Extract common Constructor.io fields
        value = item_data.get('value', '')
        data = item_data.get('data', {})
        
        # Create instance with discovered field mappings
        kwargs = {
            '_meijer_client': client,
            '_raw_data': item_data
        }
        
        # Map common fields
        field_mappings = {
            'title': item_data.get('value'),
            'product_id': item_data.get('data_id'),
            'price': item_data.get('data_price'),
            'image_url': item_data.get('data_image_url'),
            'description': item_data.get('data_description'),
            'brand': item_data.get('data_brand'),
            'product_url': item_data.get('data_url'),
        }
        
        # Apply field mappings
        for field_name, value in field_mappings.items():
            if hasattr(cls, field_name):
                kwargs[field_name] = value
        
        return cls(**{k: v for k, v in kwargs.items() if v is not None})
    
    @classmethod
    def from_product_api_response(cls, product_data: Dict[str, Any], client: Optional["MeijerComprehensiveClient"] = None) -> "MeijerItem":
        """
        Create a MeijerItem from the product API response (includes aisle information).
        
        Args:
            product_data: Raw product data from /digital/occ/v3/products/{id} endpoint
            client: Meijer client for additional operations
            
        Returns:
            MeijerItem instance with aisle information
        """
        # Extract basic product information
        kwargs = {
            'data_id': str(product_data.get('code', '')),
            'data_ean': int(product_data.get('ean', 0)),
            'data_isbopas': product_data.get('bopas', False),
            'data_isbuyable': product_data.get('buyable', False),
            'data_isalcohol': product_data.get('alcohol', False),
            'data_image_url': '',  # Will be extracted from images array
            'data_priceunit': product_data.get('unitCode', ''),
            'data_hasmperks': product_data.get('hasMPerks', False),
            'data_specialbuy': False,  # Not available in product API
            'data_description': product_data.get('description', ''),
            'data_deactivated': product_data.get('disabled', False),
            'data_productunit': product_data.get('unit', ''),
            'data_qtyincrement': int(product_data.get('qtyIncrement', 1)),
            'data_chokinghazard': product_data.get('chokingHazard', False),
            'data_ispurchasable': product_data.get('purchasable', False),
            'data_pricebyweight': product_data.get('priceByWeight', False),
            'data_mperksofferid': product_data.get('mperksOfferIds', []),
            'data_isagerestricted': product_data.get('ageRestricted', False),
            'data_ebtfoodstampable': product_data.get('ebtFoodstampable', False),
            'data_pickupavailableflag': product_data.get('availableForPickup', False),
            'data_homedeliverynotavailable': product_data.get('homeDeliveryNotAvailable', False),
            'data_requiresdiscreteinventorytracking': product_data.get('requiresDiscreteInventoryTracking', False),
            'data_sale': False,  # Not available in product API
            'data_ismap': False,  # Not available in product API
            'data_price': float(product_data.get('price', {}).get('value', 0)),
            'data_variation_id': '',  # Not available in product API
            'data_pricegoodthrough': '',  # Not available in product API
            'data_stocklevelstatus': product_data.get('stock', {}).get('stockLevelStatus', ''),
            'data_discountsalepricevalue': 0,  # Not available in product API
            'value': product_data.get('name', ''),
            'data_group_ids': [],  # Not available in product API
            'data_ingredients': product_data.get('ingredients', ''),
            'matched_terms': [],
            '_meijer_client': client,
            '_raw_data': product_data
        }
        
        # Extract image URL from images array
        images = product_data.get('images', [])
        if images:
            # Find the primary product image
            for img in images:
                if img.get('imageType') == 'PRIMARY' and img.get('format') == 'product':
                    kwargs['data_image_url'] = img.get('url', '')
                    break
            # Fallback to first image if no primary product image found
            if not kwargs['data_image_url'] and images:
                kwargs['data_image_url'] = images[0].get('url', '')
        
        # Extract aisle information from stock data and convert to colon format
        stock_data = product_data.get('stock', {})
        if stock_data:
            # Convert dash format (B-16-31-2) to colon format (B16:31)
            ilc_primary = stock_data.get('ilcPrimary', '')
            if ilc_primary and '-' in ilc_primary:
                kwargs['aisle_primary'] = cls._convert_ilc_to_colon_format(ilc_primary)
            else:
                kwargs['aisle_primary'] = ilc_primary
            
            # Convert all ILCs to colon format
            ilcs = stock_data.get('ilcs', [])
            kwargs['aisle_locations'] = [
                cls._convert_ilc_to_colon_format(ilc) for ilc in ilcs
            ]
        
        return cls(**kwargs)
    
    @staticmethod
    def _convert_ilc_to_colon_format(ilc: str) -> str:
        """
        Convert ILC from dash format (B-16-31-2) to colon format (B16:31).
        
        Args:
            ilc: ILC in dash format (e.g., "B-16-31-2")
            
        Returns:
            ILC in colon format (e.g., "B16:31")
        """
        if not ilc or '-' not in ilc:
            return ilc
        
        parts = ilc.split('-')
        if len(parts) >= 3:
            # Format: B-16-31-2 -> B16:31
            aisle_letter = parts[0]
            aisle_number = parts[1]
            section_number = parts[2]
            return f"{aisle_letter}{aisle_number}:{section_number}"
        elif len(parts) == 2:
            # Format: B-16 -> B16
            aisle_letter = parts[0]
            aisle_number = parts[1]
            return f"{aisle_letter}{aisle_number}"
        
        return ilc
    
    @property
    def title(self) -> str:
        """Get the item title/name."""
        return getattr(self, 'value', '') or getattr(self, 'title', '') or 'Unknown Item'
    
    @property
    def product_id(self) -> Optional[str]:
        """Get the product ID."""
        if hasattr(self, 'data_id'):
            return getattr(self, 'data_id', None)
        return getattr(self, 'id', None)
    
    @property
    def price(self) -> Optional[float]:
        """Get the item price."""
        price_val = getattr(self, 'data_price', None)
        if price_val:
            try:
                return float(price_val)
            except (ValueError, TypeError):
                pass
        return None
    
    @property
    def image_url(self) -> Optional[str]:
        """Get the item image URL."""
        return getattr(self, 'data_image_url', None)
    
    @property
    def brand(self) -> Optional[str]:
        """Get the item brand."""
        return getattr(self, 'data_brand', None)
    
    @property
    def aisle_display(self) -> str:
        """Get the primary aisle location in display format (e.g., 'Aisle B16 | Section 31')."""
        if not self.aisle_primary:
            return "Location Unknown"
        
        # Parse the ILC format (e.g., "B16:31" -> "Aisle B16 | Section 31")
        if ':' in self.aisle_primary:
            aisle_part, section_part = self.aisle_primary.split(':', 1)
            return f"Aisle {aisle_part} | Section {section_part}"
        
        return f"Aisle {self.aisle_primary}"
    
    @property
    def aisle_sort_key(self) -> str:
        """Get a sortable key for aisle-based sorting (e.g., 'B16:031' for sorting)."""
        if not self.aisle_primary:
            return "ZZ999:999"  # Sort unknown locations to the end
        
        # Parse the ILC format (e.g., "B16:31" -> "B16:031")
        if ':' in self.aisle_primary:
            aisle_part, section_part = self.aisle_primary.split(':', 1)
            # Pad section number with zeros for proper sorting (31 -> 031)
            return f"{aisle_part}:{section_part.zfill(3)}"
        
        return self.aisle_primary
    
    @property
    def aisle_letter(self) -> Optional[str]:
        """Get the aisle letter (e.g., 'B')."""
        if not self.aisle_primary:
            return None
        
        # Extract first character (e.g., "B16:31" -> "B")
        return self.aisle_primary[0] if self.aisle_primary else None
    
    @property
    def aisle_number(self) -> Optional[int]:
        """Get the aisle number (e.g., 16)."""
        if not self.aisle_primary:
            return None
        
        # Parse the ILC format (e.g., "B16:31" -> 16)
        if ':' in self.aisle_primary:
            aisle_part = self.aisle_primary.split(':', 1)[0]
            # Extract number after letter (e.g., "B16" -> 16)
            try:
                return int(''.join(filter(str.isdigit, aisle_part)))
            except (ValueError, TypeError):
                pass
        else:
            # Handle case without colon
            try:
                return int(''.join(filter(str.isdigit, self.aisle_primary)))
            except (ValueError, TypeError):
                pass
        
        return None
    
    @property
    def section_number(self) -> Optional[int]:
        """Get the section number (e.g., 31)."""
        if not self.aisle_primary or ':' not in self.aisle_primary:
            return None
        
        try:
            section_part = self.aisle_primary.split(':', 1)[1]
            return int(section_part)
        except (ValueError, TypeError, IndexError):
            return None
    
    def get_all_aisle_locations(self) -> List[str]:
        """Get all available aisle locations for this item."""
        locations = []
        if self.aisle_primary:
            locations.append(self.aisle_primary)
        locations.extend(self.aisle_locations)
        return list(set(locations))  # Remove duplicates
    
    def is_in_aisle(self, aisle_letter: str, aisle_number: Optional[int] = None) -> bool:
        """
        Check if this item is located in a specific aisle.
        
        Args:
            aisle_letter: Aisle letter (e.g., 'B')
            aisle_number: Optional aisle number (e.g., 16)
            
        Returns:
            True if item is in the specified aisle
        """
        if not aisle_letter:
            return False
        
        # Check primary location
        if self.aisle_primary:
            if aisle_number is None:
                # Just check aisle letter
                if self.aisle_primary.startswith(aisle_letter):
                    return True
            else:
                # Check both letter and number
                aisle_pattern = f"{aisle_letter}{aisle_number}"
                if self.aisle_primary.startswith(aisle_pattern):
                    return True
        
        # Check all locations
        for location in self.aisle_locations:
            if aisle_number is None:
                if location.startswith(aisle_letter):
                    return True
            else:
                aisle_pattern = f"{aisle_letter}{aisle_number}"
                if location.startswith(aisle_pattern):
                    return True
        
        return False
    
    def add_to_cart(self, quantity: int = 1) -> bool:
        """
        Add this item to the shopping cart.
        
        Args:
            quantity: Number of items to add
            
        Returns:
            True if successful, False otherwise
        """
        if not self._meijer_client:
            logger.warning("No Meijer client associated with item")
            return False
        
        # This would need implementation in the Meijer client
        if hasattr(self._meijer_client, 'add_to_cart'):
            return self._meijer_client.add_to_cart(self.product_id, quantity)
        
        logger.warning("Meijer client does not support add_to_cart")
        return False
    
    def get_detailed_info(self) -> Dict[str, Any]:
        """
        Get detailed product information.
        
        Returns:
            Dictionary with detailed product data
        """
        if self._raw_data:
            return self._raw_data
        
        # Return basic info from current fields
        return {
            'title': self.title,
            'product_id': self.product_id,
            'price': self.price,
            'image_url': self.image_url,
            'brand': self.brand
        }
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert item to dictionary representation."""
        result = {}
        for field_name, field_value in self.__dict__.items():
            if field_name.startswith('_'):
                continue
            result[field_name] = field_value
        return result
    
    def __str__(self) -> str:
        """String representation of the item."""
        price_str = f"${self.price:.2f}" if self.price else "Price N/A"
        brand_str = f" by {self.brand}" if self.brand else ""
        return f"MeijerItem({self.title}{brand_str}) - {price_str}"
    
    def __repr__(self) -> str:
        """Detailed representation of the item."""
        return f"MeijerItem(id={self.product_id}, title='{self.title}', price={self.price})"


# Factory function for creating MeijerItem lists from search responses
def create_meijer_items_from_search(search_response: Dict[str, Any], client: Optional["MeijerComprehensiveClient"] = None) -> List[MeijerItem]:
    """
    Create a list of MeijerItem objects from Constructor.io search response.
    
    Args:
        search_response: Response from Constructor.io search API
        client: Meijer client for additional operations
        
    Returns:
        List of MeijerItem objects
    """
    items = []
    
    # Handle different Constructor.io response structures
    results = []
    if isinstance(search_response, dict):
        if 'results' in search_response:
            results = search_response['results']
        elif 'response' in search_response and isinstance(search_response['response'], dict):
            resp = search_response['response']
            if 'results' in resp:
                results = resp['results']
    
    for item_data in results:
        try:
            item = MeijerItem.from_constructor_response(item_data, client)
            items.append(item)
        except Exception as e:
            logger.error(f"Failed to create MeijerItem from data: {e}")
            continue
    
    return items


def create_meijer_item_from_product_api(product_response: Dict[str, Any], client: Optional["MeijerComprehensiveClient"] = None) -> Optional[MeijerItem]:
    """
    Create a MeijerItem from the product API response.
    
    Args:
        product_response: Response from /digital/occ/v3/products/{id} endpoint
        client: Meijer client for additional operations
        
    Returns:
        MeijerItem instance with aisle information, or None if creation fails
    """
    try:
        return MeijerItem.from_product_api_response(product_response, client)
    except Exception as e:
        logger.error(f"Failed to create MeijerItem from product API response: {e}")
        return None


def create_meijer_items_from_product_list(product_list: List[Dict[str, Any]], client: Optional["MeijerComprehensiveClient"] = None) -> List[MeijerItem]:
    """
    Create a list of MeijerItem objects from a list of product API responses.
    
    Args:
        product_list: List of product API responses
        client: Meijer client for additional operations
        
    Returns:
        List of MeijerItem objects with aisle information
    """
    items = []
    
    for product_data in product_list:
        try:
            item = MeijerItem.from_product_api_response(product_data, client)
            if item:
                items.append(item)
        except Exception as e:
            logger.error(f"Failed to create MeijerItem from product data: {e}")
            continue
    
    return items


def sort_items_by_aisle(items: List[MeijerItem]) -> List[MeijerItem]:
    """
    Sort a list of MeijerItem objects by aisle location for defragging.
    
    Args:
        items: List of MeijerItem objects to sort
        
    Returns:
        Sorted list of MeijerItem objects
    """
    return sorted(items, key=lambda item: item.aisle_sort_key)


def group_items_by_aisle(items: List[MeijerItem]) -> Dict[str, List[MeijerItem]]:
    """
    Group MeijerItem objects by aisle location.
    
    Args:
        items: List of MeijerItem objects to group
        
    Returns:
        Dictionary with aisle keys (e.g., 'B16') and lists of items
    """
    grouped = {}
    
    for item in items:
        if item.aisle_primary:
            # Extract aisle key (e.g., "B16:31" -> "B16")
            if ':' in item.aisle_primary:
                aisle_key = item.aisle_primary.split(':', 1)[0]
            else:
                aisle_key = item.aisle_primary
            
            if aisle_key not in grouped:
                grouped[aisle_key] = []
            grouped[aisle_key].append(item)
    
    # Sort items within each aisle group
    for aisle_key in grouped:
        grouped[aisle_key] = sorted(grouped[aisle_key], key=lambda item: item.aisle_sort_key)
    
    return grouped


if __name__ == "__main__":
    print("MeijerItem class generated from Constructor.io API analysis")
    print(f"Based on analysis of Constructor.io search endpoints")
