#!/usr/bin/env python3
"""
Meijer Store Search Function using storeInfo API.

Generated from analysis of storeInfo API calls in meijer2.log.
Handles store IDs as integers with automatic string conversion.

Generated by: Claude Sonnet 4 (claude-3-5-sonnet-20241022) 
via Cursor IDE (cursor.sh) with AI assistance
"""

from typing import List, Optional, Dict, Any, Union
import requests
import json
import logging

from meijer_store_final import MeijerStore, create_meijer_stores_from_response

logger = logging.getLogger(__name__)


class MeijerStoreSearch:
    """
    Meijer store search functionality using storeInfo API.
    
    This class provides store search by location and store details lookup
    by interfacing with Meijer's storeInfo API endpoints.
    
    Properly handles store IDs as integers with automatic type conversion.
    """
    
    def __init__(self, meijer_client=None):
        """
        Initialize the store search interface.
        
        Args:
            meijer_client: Associated Meijer client for authentication
        """
        self.meijer_client = meijer_client
        
        # StoreInfo API configuration (discovered from analysis)
        self.base_url = "https://api.meijer.com/digital"
        
        # Common parameters from analysis
        self.default_params = {
            "dataVariant": 2,  # Discovered from API calls
        }
    
    def find_stores_nearby(self, 
                          latitude: float, 
                          longitude: float,
                          radius_miles: int = 50,
                          max_results: int = 10) -> List[MeijerStore]:
        """
        Find Meijer stores near given coordinates.
        
        Args:
            latitude: Search latitude
            longitude: Search longitude  
            radius_miles: Search radius in miles
            max_results: Maximum number of stores to return
            
        Returns:
            List of MeijerStore objects sorted by distance
        """
        endpoint = f"{self.base_url}/storeInfo/v2/stores/proximity"
        
        # Build parameters based on API analysis
        params = {
            "latitude": latitude,
            "longitude": longitude,
            "miles": radius_miles,
            "numToReturn": max_results,
            **self.default_params
        }
        
        try:
            response = requests.get(endpoint, params=params)
            response.raise_for_status()
            
            store_data = response.json()
            stores = create_meijer_stores_from_response(store_data, self.meijer_client)
            
            logger.info(f"Found {len(stores)} stores within {radius_miles} miles of ({latitude}, {longitude})")
            return stores
            
        except Exception as e:
            logger.error(f"Store proximity search failed: {e}")
            return []
    
    def get_store_details(self, store_id: Union[int, str]) -> Optional[MeijerStore]:
        """
        Get detailed information for a specific store.
        
        Args:
            store_id: Meijer store ID (int or str, automatically converted to int)
            
        Returns:
            MeijerStore object with detailed information, or None if not found
        """
        # Convert store_id to int - this is the proper type!
        try:
            if isinstance(store_id, str):
                store_id_int = int(store_id)
                logger.debug(f"Converted string store_id '{store_id}' to int {store_id_int}")
            elif isinstance(store_id, int):
                store_id_int = store_id
            else:
                logger.error(f"Invalid store_id type: {type(store_id)}. Expected int or str.")
                return None
        except (ValueError, TypeError) as e:
            logger.error(f"Could not convert store_id '{store_id}' to int: {e}")
            return None
        
        endpoint = f"{self.base_url}/storeInfo/stores/{store_id_int}"
        
        try:
            response = requests.get(endpoint)
            response.raise_for_status()
            
            store_data = response.json()
            stores = create_meijer_stores_from_response(store_data, self.meijer_client)
            
            if stores:
                store = stores[0]
                logger.info(f"Retrieved details for store {store_id_int}: {store.display_name}")
                return store
            else:
                logger.warning(f"No store data found for store {store_id_int}")
                return None
                
        except Exception as e:
            logger.error(f"Store details lookup failed for {store_id_int}: {e}")
            return None
    
    def find_stores_in_city(self, city: str, state: str, max_results: int = 20) -> List[MeijerStore]:
        """
        Find stores in a specific city (requires geocoding).
        
        Args:
            city: City name
            state: State abbreviation
            max_results: Maximum stores to return
            
        Returns:
            List of MeijerStore objects
        """
        # This would require a geocoding service to convert city/state to coordinates
        # For now, return example implementation
        logger.warning("City-based search requires geocoding service integration")
        return []
    
    def get_all_stores(self, max_radius: int = 3000, max_results: int = 20) -> List[MeijerStore]:
        """
        Get all Meijer stores (using large radius).
        
        Args:
            max_radius: Large radius to capture all stores
            max_results: Maximum stores to return
            
        Returns:
            List of all MeijerStore objects
        """
        # Use a central US location for wide search
        # (Based on coordinates seen in analysis)
        central_lat = 42.8289  # Michigan area from analysis
        central_lng = -86.0905
        
        return self.find_stores_nearby(
            latitude=central_lat,
            longitude=central_lng, 
            radius_miles=max_radius,
            max_results=max_results
        )
    
    def get_stores_by_ids(self, store_ids: List[Union[int, str]]) -> List[MeijerStore]:
        """
        Get multiple stores by their IDs.
        
        Args:
            store_ids: List of store IDs (int or str, automatically converted)
            
        Returns:
            List of MeijerStore objects
        """
        stores = []
        
        for store_id in store_ids:
            store = self.get_store_details(store_id)
            if store:
                stores.append(store)
        
        return stores
    
    def find_stores_with_service(self, service_type: str, **search_kwargs) -> List[MeijerStore]:
        """
        Find stores that offer a specific service.
        
        Args:
            service_type: Type of service ('pharmacy', 'gas', 'curbside', 'delivery', 'alcohol', '24hour')
            **search_kwargs: Additional arguments for find_stores_nearby()
            
        Returns:
            List of MeijerStore objects with the specified service
        """
        # Default search parameters
        search_params = {
            'latitude': 42.8289,
            'longitude': -86.0905,
            'radius_miles': 3000,
            'max_results': 50
        }
        search_params.update(search_kwargs)
        
        # Get all stores in area
        all_stores = self.find_stores_nearby(**search_params)
        
        # Filter by service type
        service_filters = {
            'pharmacy': lambda s: s.has_pharmacy(),
            'gas': lambda s: s.has_gas_station(),
            'curbside': lambda s: s.has_curbside_pickup(),
            'delivery': lambda s: s.has_delivery(),
            'alcohol': lambda s: s.has_alcohol_sales(),
            '24hour': lambda s: s.is_24_hours()
        }
        
        if service_type.lower() not in service_filters:
            logger.warning(f"Unknown service type: {service_type}")
            return []
        
        filter_func = service_filters[service_type.lower()]
        filtered_stores = [store for store in all_stores if filter_func(store)]
        
        logger.info(f"Found {len(filtered_stores)} stores with {service_type} service")
        return filtered_stores


# Convenience functions with proper type handling
def get_store_details(store_id: Union[int, str]) -> Optional[MeijerStore]:
    """
    Convenience function to get store details.
    
    Args:
        store_id: Store ID (int or str, automatically converted to int)
        
    Returns:
        MeijerStore object or None
    """
    search = MeijerStoreSearch()
    return search.get_store_details(store_id)


def find_stores_nearby(latitude: float, longitude: float, **kwargs) -> List[MeijerStore]:
    """
    Convenience function to find nearby stores.
    
    Args:
        latitude: Search latitude
        longitude: Search longitude
        **kwargs: Additional search parameters
        
    Returns:
        List of MeijerStore objects
    """
    search = MeijerStoreSearch()
    return search.find_stores_nearby(latitude, longitude, **kwargs)


def find_pharmacy_stores(**search_kwargs) -> List[MeijerStore]:
    """Find stores with pharmacy services."""
    search = MeijerStoreSearch()
    return search.find_stores_with_service('pharmacy', **search_kwargs)


def find_gas_stations(**search_kwargs) -> List[MeijerStore]:
    """Find stores with gas stations."""
    search = MeijerStoreSearch()
    return search.find_stores_with_service('gas', **search_kwargs)


def find_24hour_stores(**search_kwargs) -> List[MeijerStore]:
    """Find 24-hour stores."""
    search = MeijerStoreSearch()
    return search.find_stores_with_service('24hour', **search_kwargs)


# Integration with main Meijer client
class MeijerWithStores:
    """
    Extended Meijer client with store search functionality.
    """
    
    def __init__(self, meijer_client):
        """Initialize with existing Meijer client."""
        self.meijer_client = meijer_client
        self.store_search = MeijerStoreSearch(meijer_client)
    
    def find_nearby_stores(self, latitude: float, longitude: float, **kwargs) -> List[MeijerStore]:
        """Find stores near coordinates."""
        return self.store_search.find_stores_nearby(latitude, longitude, **kwargs)
    
    def get_store(self, store_id: Union[int, str]) -> Optional[MeijerStore]:
        """Get specific store details with automatic type conversion."""
        return self.store_search.get_store_details(store_id)
    
    def find_all_stores(self, **kwargs) -> List[MeijerStore]:
        """Get all Meijer stores."""
        return self.store_search.get_all_stores(**kwargs)
    
    def find_stores_with_service(self, service_type: str, **kwargs) -> List[MeijerStore]:
        """Find stores with specific service."""
        return self.store_search.find_stores_with_service(service_type, **kwargs)


if __name__ == "__main__":
    # Example usage showing proper int/string handling
    store_search = MeijerStoreSearch()
    
    print("🏪 Meijer Store Search - Proper Type Handling")
    print("=" * 60)
    
    # Test both int and string store IDs
    test_store_ids = [217, "217", 152, "152"]
    
    print("🔍 Testing store ID type handling:")
    for store_id in test_store_ids:
        print(f"\n📋 Getting store details for {store_id} (type: {type(store_id).__name__}):")
        
        # This should work for both int and string
        store = store_search.get_store_details(store_id)
        if store:
            print(f"   ✅ Found: {store.display_name} (ID: {store.store_id}, type: {type(store.store_id).__name__})")
        else:
            print(f"   ❌ Store not found")
    
    # Find stores near a location (coordinates from analysis)
    print(f"\n🔍 Finding stores near Michigan:")
    stores = store_search.find_stores_nearby(
        latitude=42.82893, 
        longitude=-86.09048,
        radius_miles=50,
        max_results=5
    )
    
    print(f"📍 Found {len(stores)} stores:")
    for store in stores:
        print(f"   - Store {store.store_id}: {store.display_name} ({store.distance_miles:.1f} mi)")
    
    # Test convenience functions
    print(f"\n🏥 Finding pharmacy stores:")
    pharmacy_stores = find_pharmacy_stores(radius_miles=100, max_results=3)
    for store in pharmacy_stores:
        print(f"   - {store.display_name}: {store.pharm_phone or 'No pharmacy phone'}")
    
    print(f"\n⛽ Finding gas stations:")
    gas_stores = find_gas_stations(radius_miles=100, max_results=3)
    for store in gas_stores:
        gas_status = "Available" if store.has_gas_station() else "Not available"
        print(f"   - {store.display_name}: Gas {gas_status}") 