#!/usr/bin/env python3
"""
Store Information Analyzer for Meijer storeInfo endpoints.

Analyzes storeInfo API calls from meijer2.log to understand store data structures
and build comprehensive MeijerStore classes with all store information.

Generated by: Claude Sonnet 4 (claude-3-5-sonnet-20241022)
via Cursor IDE (cursor.sh) with AI assistance
"""

import json
import logging
from pathlib import Path
from typing import Dict, List, Any, Optional, Union
from collections import defaultdict, Counter
from dataclasses import dataclass, field
from datetime import datetime
from urllib.parse import urlparse, parse_qs

# Import mitmproxy modules
try:
    from mitmproxy import flow
    from mitmproxy import http
    from mitmproxy.io import FlowReader
except ImportError as e:
    print(f"Error importing mitmproxy modules: {e}")
    print("Make sure you're in the virtual environment: source venv/bin/activate")
    exit(1)


@dataclass
class StoreInfoAnalysis:
    """Analysis results for storeInfo API calls."""

    proximity_calls: List[Dict[str, Any]] = field(default_factory=list)
    specific_store_calls: List[Dict[str, Any]] = field(default_factory=list)

    store_structures: List[Dict[str, Any]] = field(default_factory=list)
    unique_store_fields: Counter = field(default_factory=Counter)
    field_data_types: Dict[str, str] = field(default_factory=dict)

    api_parameters: Dict[str, Counter] = field(
        default_factory=lambda: defaultdict(Counter)
    )
    store_ids_found: List[str] = field(default_factory=list)
    coordinates: List[Dict[str, float]] = field(default_factory=list)

    api_endpoints: Dict[str, int] = field(default_factory=lambda: defaultdict(int))


class StoreInfoAnalyzer:
    """
    Specialized analyzer for storeInfo endpoints.

    Analyzes how Meijer uses storeInfo APIs for store search and details
    and extracts store structures to build comprehensive MeijerStore classes.
    """

    def __init__(self, log_file_path: str):
        self.log_file_path = Path(log_file_path)
        self.flows = []
        self.analysis = StoreInfoAnalysis()

        # Setup logging
        logging.basicConfig(level=logging.INFO)
        self.logger = logging.getLogger(__name__)

        # StoreInfo endpoint patterns
        self.store_endpoints = {
            "proximity": "/storeInfo/v2/stores/proximity",
            "specific_store": "/storeInfo/stores/",
        }

    def load_flows(self) -> bool:
        """Load flows from the mitmproxy log file."""
        try:
            if not self.log_file_path.exists():
                self.logger.error(f"Log file not found: {self.log_file_path}")
                return False

            self.logger.info(f"Loading flows from: {self.log_file_path}")

            with open(self.log_file_path, "rb") as f:
                reader = FlowReader(f)

                flow_count = 0
                for flow_obj in reader.stream():
                    self.flows.append(flow_obj)
                    flow_count += 1

                    if flow_count % 1000 == 0:
                        self.logger.info(f"Loaded {flow_count} flows...")

                self.logger.info(f"Successfully loaded {len(self.flows)} flows")
                return True

        except Exception as e:
            self.logger.error(f"Error loading flows: {e}")
            return False

    def analyze_store_info_flows(self) -> None:
        """Analyze flows specifically for storeInfo endpoints."""
        self.logger.info("Starting storeInfo flow analysis...")

        store_info_flow_count = 0

        for i, flow_obj in enumerate(self.flows):
            try:
                if not isinstance(flow_obj, http.HTTPFlow):
                    continue

                request = flow_obj.request
                response = flow_obj.response

                if not hasattr(request, "pretty_url") or not request.pretty_url:
                    continue

                url_str = request.pretty_url

                # Check if this is a storeInfo endpoint
                if "storeInfo" in url_str:
                    store_info_flow_count += 1
                    endpoint_type = self._get_store_endpoint_type(url_str)
                    self._analyze_store_info_flow(flow_obj, endpoint_type)

                if (i + 1) % 1000 == 0:
                    self.logger.info(f"Analyzed {i + 1}/{len(self.flows)} flows...")

            except Exception as e:
                self.logger.error(f"Error analyzing flow {i}: {e}")

        self.logger.info(f"Found {store_info_flow_count} storeInfo flows")
        self._analyze_store_patterns()

    def _get_store_endpoint_type(self, url_str: str) -> str:
        """Determine the storeInfo endpoint type."""
        if "/storeInfo/v2/stores/proximity" in url_str:
            return "proximity"
        elif "/storeInfo/stores/" in url_str:
            return "specific_store"
        return "unknown"

    def _analyze_store_info_flow(
        self, flow_obj: http.HTTPFlow, endpoint_type: str
    ) -> None:
        """Analyze a single storeInfo flow."""
        request = flow_obj.request
        response = flow_obj.response

        # Parse URL components
        parsed_url = urlparse(request.pretty_url)
        query_params = parse_qs(parsed_url.query)

        flow_data = {
            "url": request.pretty_url,
            "method": request.method,
            "status_code": response.status_code if response else None,
            "timestamp": getattr(flow_obj, "timestamp_start", None),
            "path": parsed_url.path,
            "query_params": query_params,
            "request_headers": dict(request.headers)
            if hasattr(request, "headers")
            else {},
            "response_headers": dict(response.headers)
            if response and hasattr(response, "headers")
            else {},
            "request_body": self._extract_and_parse_body(request),
            "response_body": self._extract_and_parse_body(response)
            if response
            else None,
        }

        # Count endpoint usage
        self.analysis.api_endpoints[endpoint_type] += 1

        # Store flow data by endpoint type
        if endpoint_type == "proximity":
            self.analysis.proximity_calls.append(flow_data)
            # Extract location parameters
            self._extract_location_data(flow_data)

        elif endpoint_type == "specific_store":
            self.analysis.specific_store_calls.append(flow_data)
            # Extract store ID from path
            store_id = self._extract_store_id(flow_data["path"])
            if store_id and store_id not in self.analysis.store_ids_found:
                self.analysis.store_ids_found.append(store_id)

        # Track API parameters
        for param, values in query_params.items():
            if values:
                self.analysis.api_parameters[param][values[0]] += 1

        # Extract store structures from response
        if response and flow_data["response_body"]:
            self._extract_store_structures(flow_data["response_body"], endpoint_type)

    def _extract_location_data(self, flow_data: Dict[str, Any]) -> None:
        """Extract location data from proximity search."""
        query_params = flow_data.get("query_params", {})

        try:
            latitude = query_params.get("latitude", [None])[0]
            longitude = query_params.get("longitude", [None])[0]

            if latitude and longitude:
                coord_data = {
                    "latitude": float(latitude),
                    "longitude": float(longitude),
                    "miles": float(query_params.get("miles", [0])[0]),
                    "numToReturn": int(query_params.get("numToReturn", [0])[0]),
                    "dataVariant": int(query_params.get("dataVariant", [0])[0]),
                }
                self.analysis.coordinates.append(coord_data)
        except (ValueError, TypeError):
            pass

    def _extract_store_id(self, path: str) -> Optional[str]:
        """Extract store ID from path."""
        # Path like /digital/storeInfo/stores/217
        if "/storeInfo/stores/" in path:
            parts = path.split("/storeInfo/stores/")
            if len(parts) > 1:
                store_id = parts[1].split("/")[
                    0
                ]  # Handle potential additional path parts
                return store_id
        return None

    def _extract_and_parse_body(self, http_obj) -> Union[Dict, List, str, None]:
        """Extract and parse HTTP body content."""
        try:
            if hasattr(http_obj, "content") and http_obj.content:
                try:
                    text_content = http_obj.content.decode("utf-8")
                    try:
                        return json.loads(text_content)
                    except json.JSONDecodeError:
                        return text_content
                except UnicodeDecodeError:
                    hex_content = http_obj.content.hex()
                    return (
                        hex_content[:200] + "..."
                        if len(hex_content) > 200
                        else hex_content
                    )
        except Exception:
            pass
        return None

    def _extract_store_structures(
        self, response_data: Union[Dict, List, str], endpoint_type: str
    ) -> None:
        """Extract and analyze store structures from storeInfo responses."""
        if not isinstance(response_data, dict):
            return

        # Look for stores in different response structures
        stores = []

        # Common storeInfo response structures
        if "store" in response_data:  # Meijer uses 'store' not 'stores'
            stores = response_data["store"]
        elif "stores" in response_data:
            stores = response_data["stores"]
        elif "data" in response_data:
            data = response_data["data"]
            if isinstance(data, dict) and "stores" in data:
                stores = data["stores"]
            elif isinstance(data, dict) and "store" in data:
                stores = data["store"]
            elif isinstance(data, list):
                stores = data
        elif isinstance(response_data, list):
            stores = response_data

        # For specific store endpoint, the response might be a single store object
        if endpoint_type == "specific_store" and not stores:
            if (
                "storeId" in response_data
                or "id" in response_data
                or "StoreId" in response_data
            ):
                stores = [response_data]

        # Analyze each store
        for store in stores:
            if isinstance(store, dict):
                self._analyze_single_store(store, endpoint_type)
                self.analysis.store_structures.append(store)

    def _analyze_single_store(self, store: Dict[str, Any], endpoint_type: str) -> None:
        """Analyze a single store structure to understand fields and types."""

        # Flatten nested structures for field analysis
        def flatten_dict(d, parent_key="", sep="_"):
            """Flatten nested dictionary."""
            items = []
            for k, v in d.items():
                new_key = f"{parent_key}{sep}{k}" if parent_key else k
                if isinstance(v, dict):
                    items.extend(flatten_dict(v, new_key, sep=sep).items())
                elif isinstance(v, list) and v and isinstance(v[0], dict):
                    # For lists of dicts, analyze the first item
                    items.extend(flatten_dict(v[0], f"{new_key}_item", sep=sep).items())
                else:
                    items.append((new_key, v))
            return dict(items)

        flattened = flatten_dict(store)

        # Analyze all fields
        for field_name, field_value in flattened.items():
            # Count field frequency
            self.analysis.unique_store_fields[field_name] += 1

            # Determine and store data type
            field_type = type(field_value).__name__
            if field_name not in self.analysis.field_data_types:
                self.analysis.field_data_types[field_name] = field_type
            elif self.analysis.field_data_types[field_name] != field_type:
                # Handle mixed types
                existing_type = self.analysis.field_data_types[field_name]
                if not existing_type.startswith("Union"):
                    self.analysis.field_data_types[field_name] = (
                        f"Union[{existing_type}, {field_type}]"
                    )

    def _analyze_store_patterns(self) -> None:
        """Analyze patterns in storeInfo API usage."""
        # Analyze proximity search patterns
        if self.analysis.coordinates:
            unique_locations = set()
            for coord in self.analysis.coordinates:
                unique_locations.add((coord["latitude"], coord["longitude"]))

            self.logger.info(f"Found {len(unique_locations)} unique search locations")

            # Common search parameters
            miles_values = [coord["miles"] for coord in self.analysis.coordinates]
            num_return_values = [
                coord["numToReturn"] for coord in self.analysis.coordinates
            ]

            self.logger.info(f"Search radius values: {set(miles_values)}")
            self.logger.info(f"Results requested: {set(num_return_values)}")

    def generate_meijer_store_class(self) -> str:
        """Generate MeijerStore class based on analyzed store structures."""
        # Get the most common fields
        sorted_fields = sorted(
            self.analysis.unique_store_fields.items(), key=lambda x: x[1], reverse=True
        )

        class_definition = '''#!/usr/bin/env python3
"""
MeijerStore class generated from storeInfo API analysis.

This class represents Meijer store information returned from storeInfo endpoints
and includes all discovered fields from the API responses.

Generated by analyzing meijer2.log storeInfo endpoints.
"""

from typing import Optional, Union, List, Dict, Any, TYPE_CHECKING
from dataclasses import dataclass, field
from datetime import datetime
import json
import logging

if TYPE_CHECKING:
    from meijer_comprehensive import MeijerComprehensiveClient

logger = logging.getLogger(__name__)


@dataclass
class MeijerStore:
    """
    Represents a Meijer store from storeInfo API results.
    
    This class contains all fields discovered from storeInfo API analysis
    and provides methods for interacting with store information.
    """
    
'''

        # Add field definitions based on analysis
        core_fields = [
            "id",
            "storeId",
            "name",
            "address",
            "phone",
        ]  # Prioritize core fields

        # Add core fields first
        for field_name, frequency in sorted_fields:
            if any(core in field_name.lower() for core in core_fields):
                field_type = self._convert_to_python_type(
                    self.analysis.field_data_types.get(field_name, "Any")
                )
                python_field_name = self._to_snake_case(field_name)

                # Determine if field should be optional
                total_stores = len(self.analysis.store_structures)
                is_optional = frequency < total_stores * 0.8  # Less than 80% presence

                if is_optional and not field_type.startswith("Optional"):
                    field_type = f"Optional[{field_type}]"

                default_value = " = None" if is_optional else ""
                class_definition += (
                    f"    {python_field_name}: {field_type}{default_value}\n"
                )

        # Add other important fields
        for field_name, frequency in sorted_fields[:30]:  # Top 30 fields
            if not any(core in field_name.lower() for core in core_fields):
                field_type = self._convert_to_python_type(
                    self.analysis.field_data_types.get(field_name, "Any")
                )
                python_field_name = self._to_snake_case(field_name)

                # Skip if already added
                if python_field_name in class_definition:
                    continue

                total_stores = len(self.analysis.store_structures)
                is_optional = frequency < total_stores * 0.8

                if is_optional and not field_type.startswith("Optional"):
                    field_type = f"Optional[{field_type}]"

                default_value = " = None" if is_optional else ""
                class_definition += (
                    f"    {python_field_name}: {field_type}{default_value}\n"
                )

        # Add internal fields
        class_definition += "\n    # Internal fields\n"
        class_definition += '    _meijer_client: Optional["MeijerComprehensiveClient"] = field(default=None, repr=False)\n'
        class_definition += "    _raw_data: Optional[Dict[str, Any]] = field(default=None, repr=False)\n"

        # Add methods
        class_definition += '''
    @classmethod
    def from_store_info_response(cls, store_data: Dict[str, Any], client: Optional["MeijerComprehensiveClient"] = None) -> "MeijerStore":
        """
        Create a MeijerStore from storeInfo API response data.
        
        Args:
            store_data: Raw store data from storeInfo API response
            client: Meijer client for additional operations
            
        Returns:
            MeijerStore instance
        """
        # Create instance with discovered field mappings
        kwargs = {
            '_meijer_client': client,
            '_raw_data': store_data
        }
        
        # Map storeInfo response fields to dataclass fields
        field_mappings = {'''

        # Add field mappings for common storeInfo fields discovered
        common_mappings = [
            ("storeId", "store_id"),
            ("id", "store_id"),
            ("name", "name"),
            ("address", "address"),
            ("phone", "phone"),
            ("latitude", "latitude"),
            ("longitude", "longitude"),
            ("distance", "distance"),
            ("isOpen", "is_open"),
            ("storeHours", "store_hours"),
        ]

        for src_field, dst_field in common_mappings:
            class_definition += (
                f"\n            '{dst_field}': store_data.get('{src_field}'),"
            )

        class_definition += '''
        }
        
        # Apply direct field mappings
        for python_field, api_value in field_mappings.items():
            if hasattr(cls, python_field) and api_value is not None:
                kwargs[python_field] = api_value
        
        # Handle nested structures
        if 'address' in store_data and isinstance(store_data['address'], dict):
            address_data = store_data['address']
            kwargs.update({
                'address_line1': address_data.get('line1'),
                'address_line2': address_data.get('line2'),
                'address_city': address_data.get('city'),
                'address_state': address_data.get('state'),
                'address_zipcode': address_data.get('zipCode'),
                'address_country': address_data.get('country')
            })
        
        return cls(**{k: v for k, v in kwargs.items() if hasattr(cls, k) and v is not None})
    
    @property
    def store_id(self) -> str:
        """Get the store ID."""
        return getattr(self, 'id', '') or getattr(self, 'storeid', '') or getattr(self, 'store_id', '')
    
    @property
    def display_name(self) -> str:
        """Get the store display name."""
        return getattr(self, 'name', '') or f"Meijer Store {self.store_id}"
    
    @property
    def full_address(self) -> str:
        """Get the complete formatted address."""
        address_parts = []
        
        if hasattr(self, 'address_line1') and self.address_line1:
            address_parts.append(self.address_line1)
        if hasattr(self, 'address_line2') and self.address_line2:
            address_parts.append(self.address_line2)
        
        city_state_zip = []
        if hasattr(self, 'address_city') and self.address_city:
            city_state_zip.append(self.address_city)
        if hasattr(self, 'address_state') and self.address_state:
            city_state_zip.append(self.address_state)
        if hasattr(self, 'address_zipcode') and self.address_zipcode:
            city_state_zip.append(str(self.address_zipcode))
        
        if city_state_zip:
            address_parts.append(', '.join(city_state_zip))
        
        return ', '.join(address_parts) if address_parts else 'Address not available'
    
    @property
    def coordinates(self) -> Optional[Dict[str, float]]:
        """Get store coordinates."""
        lat = getattr(self, 'latitude', None)
        lng = getattr(self, 'longitude', None)
        
        if lat is not None and lng is not None:
            return {'latitude': float(lat), 'longitude': float(lng)}
        return None
    
    @property
    def distance_miles(self) -> Optional[float]:
        """Get distance in miles (if from proximity search)."""
        distance = getattr(self, 'distance', None)
        if distance is not None:
            try:
                return float(distance)
            except (ValueError, TypeError):
                pass
        return None
    
    def is_open_now(self) -> bool:
        """Check if store is currently open."""
        is_open = getattr(self, 'is_open', None)
        if is_open is not None:
            return bool(is_open)
        
        # Could implement store hours checking logic here
        return True  # Default assumption
    
    def get_store_hours(self) -> Dict[str, Any]:
        """Get store hours information."""
        hours = getattr(self, 'store_hours', None)
        if hours:
            return hours if isinstance(hours, dict) else {}
        
        return {}
    
    def get_store_services(self) -> List[str]:
        """Get list of store services."""
        services = []
        
        # Check for common service flags discovered in analysis
        service_fields = [
            ('pharmacy', 'Pharmacy'),
            ('gas_station', 'Gas Station'),
            ('grocery_pickup', 'Grocery Pickup'),
            ('home_delivery', 'Home Delivery'),
            ('liquor', 'Liquor Store')
        ]
        
        for field_name, service_name in service_fields:
            if hasattr(self, field_name) and getattr(self, field_name):
                services.append(service_name)
        
        return services
    
    def get_contact_info(self) -> Dict[str, str]:
        """Get store contact information."""
        contact = {}
        
        if hasattr(self, 'phone') and self.phone:
            contact['phone'] = self.phone
        
        contact['address'] = self.full_address
        
        if self.coordinates:
            contact['coordinates'] = f"{self.coordinates['latitude']}, {self.coordinates['longitude']}"
        
        return contact
    
    def calculate_distance_to(self, latitude: float, longitude: float) -> Optional[float]:
        """
        Calculate distance to given coordinates (if store coordinates are available).
        
        Args:
            latitude: Target latitude
            longitude: Target longitude
            
        Returns:
            Distance in miles, or None if store coordinates not available
        """
        if not self.coordinates:
            return None
        
        # Simple distance calculation (Haversine formula would be more accurate)
        import math
        
        store_lat = math.radians(self.coordinates['latitude'])
        store_lng = math.radians(self.coordinates['longitude'])
        target_lat = math.radians(latitude)
        target_lng = math.radians(longitude)
        
        dlat = target_lat - store_lat
        dlng = target_lng - store_lng
        
        a = math.sin(dlat/2)**2 + math.cos(store_lat) * math.cos(target_lat) * math.sin(dlng/2)**2
        c = 2 * math.asin(math.sqrt(a))
        
        # Earth's radius in miles
        radius_miles = 3956
        
        return c * radius_miles
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert store to dictionary representation."""
        result = {}
        for field_name, field_value in self.__dict__.items():
            if field_name.startswith('_'):
                continue
            result[field_name] = field_value
        return result
    
    def __str__(self) -> str:
        """String representation of the store."""
        distance_str = f" ({self.distance_miles:.1f} mi)" if self.distance_miles else ""
        return f"MeijerStore({self.display_name}{distance_str}) - {self.full_address}"
    
    def __repr__(self) -> str:
        """Detailed representation of the store."""
        return f"MeijerStore(id={self.store_id}, name='{self.display_name}', coordinates={self.coordinates})"


# Factory function for creating MeijerStore lists from storeInfo responses
def create_meijer_stores_from_response(response_data: Dict[str, Any], client: Optional["MeijerComprehensiveClient"] = None) -> List[MeijerStore]:
    """
    Create a list of MeijerStore objects from storeInfo API response.
    
    Args:
        response_data: Response from storeInfo API
        client: Meijer client for additional operations
        
    Returns:
        List of MeijerStore objects
    """
    stores = []
    
    # Handle different storeInfo response structures
    store_data_list = []
    
    if isinstance(response_data, dict):
        if 'stores' in response_data:
            store_data_list = response_data['stores']
        elif 'data' in response_data:
            data = response_data['data']
            if isinstance(data, dict) and 'stores' in data:
                store_data_list = data['stores']
            elif isinstance(data, list):
                store_data_list = data
        elif 'storeId' in response_data or 'id' in response_data:
            # Single store response
            store_data_list = [response_data]
    elif isinstance(response_data, list):
        store_data_list = response_data
    
    for store_data in store_data_list:
        try:
            store = MeijerStore.from_store_info_response(store_data, client)
            stores.append(store)
        except Exception as e:
            logger.error(f"Failed to create MeijerStore from data: {e}")
            continue
    
    return stores


if __name__ == "__main__":
    print("MeijerStore class generated from storeInfo API analysis")
    print(f"Based on analysis of storeInfo endpoints")
'''

        return class_definition

    def _convert_to_python_type(self, type_str: str) -> str:
        """Convert discovered types to proper Python types."""
        type_map = {
            "str": "str",
            "int": "int",
            "float": "float",
            "bool": "bool",
            "list": "List[Any]",
            "dict": "Dict[str, Any]",
            "NoneType": "None",
        }

        if type_str.startswith("Union["):
            return type_str

        return type_map.get(type_str, "Any")

    def _to_snake_case(self, camel_str: str) -> str:
        """Convert camelCase or other formats to snake_case."""
        import re

        # Handle common patterns
        s1 = re.sub("(.)([A-Z][a-z]+)", r"\1_\2", camel_str)
        s2 = re.sub("([a-z0-9])([A-Z])", r"\1_\2", s1)
        return s2.lower().replace("-", "_").replace(" ", "_")

    def generate_store_search_function(self) -> str:
        """Generate store search function based on storeInfo API patterns."""

        search_function = '''#!/usr/bin/env python3
"""
Meijer Store Search Function using storeInfo API.

Generated from analysis of storeInfo API calls in meijer2.log.
"""

from typing import List, Optional, Dict, Any
import requests
import json
import logging

from meijer_store import MeijerStore, create_meijer_stores_from_response

logger = logging.getLogger(__name__)


class MeijerStoreSearch:
    """
    Meijer store search functionality using storeInfo API.
    
    This class provides store search by location and store details lookup
    by interfacing with Meijer's storeInfo API endpoints.
    """
    
    def __init__(self, meijer_client=None):
        """
        Initialize the store search interface.
        
        Args:
            meijer_client: Associated Meijer client for authentication
        """
        self.meijer_client = meijer_client
        
        # StoreInfo API configuration (discovered from analysis)
        self.base_url = "https://api.meijer.com/digital"
        
        # Common parameters from analysis
        self.default_params = {
            "dataVariant": 2,  # Discovered from API calls
        }
    
    def find_stores_nearby(self, 
                          latitude: float, 
                          longitude: float,
                          radius_miles: int = 50,
                          max_results: int = 10) -> List[MeijerStore]:
        """
        Find Meijer stores near given coordinates.
        
        Args:
            latitude: Search latitude
            longitude: Search longitude  
            radius_miles: Search radius in miles
            max_results: Maximum number of stores to return
            
        Returns:
            List of MeijerStore objects sorted by distance
        """
        endpoint = f"{self.base_url}/storeInfo/v2/stores/proximity"
        
        # Build parameters based on API analysis
        params = {
            "latitude": latitude,
            "longitude": longitude,
            "miles": radius_miles,
            "numToReturn": max_results,
            **self.default_params
        }
        
        try:
            response = requests.get(endpoint, params=params)
            response.raise_for_status()
            
            store_data = response.json()
            stores = create_meijer_stores_from_response(store_data, self.meijer_client)
            
            logger.info(f"Found {len(stores)} stores within {radius_miles} miles of ({latitude}, {longitude})")
            return stores
            
        except Exception as e:
            logger.error(f"Store proximity search failed: {e}")
            return []
    
    def get_store_details(self, store_id: str) -> Optional[MeijerStore]:
        """
        Get detailed information for a specific store.
        
        Args:
            store_id: Meijer store ID
            
        Returns:
            MeijerStore object with detailed information, or None if not found
        """
        endpoint = f"{self.base_url}/storeInfo/stores/{store_id}"
        
        try:
            response = requests.get(endpoint)
            response.raise_for_status()
            
            store_data = response.json()
            stores = create_meijer_stores_from_response(store_data, self.meijer_client)
            
            if stores:
                logger.info(f"Retrieved details for store {store_id}")
                return stores[0]
            else:
                logger.warning(f"No store data found for store {store_id}")
                return None
                
        except Exception as e:
            logger.error(f"Store details lookup failed for {store_id}: {e}")
            return None
    
    def find_stores_in_city(self, city: str, state: str, max_results: int = 20) -> List[MeijerStore]:
        """
        Find stores in a specific city (requires geocoding).
        
        Args:
            city: City name
            state: State abbreviation
            max_results: Maximum stores to return
            
        Returns:
            List of MeijerStore objects
        """
        # This would require a geocoding service to convert city/state to coordinates
        # For now, return example implementation
        logger.warning("City-based search requires geocoding service integration")
        return []
    
    def get_all_stores(self, max_radius: int = 3000, max_results: int = 20) -> List[MeijerStore]:
        """
        Get all Meijer stores (using large radius).
        
        Args:
            max_radius: Large radius to capture all stores
            max_results: Maximum stores to return
            
        Returns:
            List of all MeijerStore objects
        """
        # Use a central US location for wide search
        # (Based on coordinates seen in analysis)
        central_lat = 42.8289  # Michigan area from analysis
        central_lng = -86.0905
        
        return self.find_stores_nearby(
            latitude=central_lat,
            longitude=central_lng, 
            radius_miles=max_radius,
            max_results=max_results
        )
    
    def get_stores_by_ids(self, store_ids: List[str]) -> List[MeijerStore]:
        """
        Get multiple stores by their IDs.
        
        Args:
            store_ids: List of store IDs to retrieve
            
        Returns:
            List of MeijerStore objects
        """
        stores = []
        
        for store_id in store_ids:
            store = self.get_store_details(store_id)
            if store:
                stores.append(store)
        
        return stores


# Integration with main Meijer client
class MeijerWithStores:
    """
    Extended Meijer client with store search functionality.
    """
    
    def __init__(self, meijer_client):
        """Initialize with existing Meijer client."""
        self.meijer_client = meijer_client
        self.store_search = MeijerStoreSearch(meijer_client)
    
    def find_nearby_stores(self, latitude: float, longitude: float, **kwargs) -> List[MeijerStore]:
        """Find stores near coordinates."""
        return self.store_search.find_stores_nearby(latitude, longitude, **kwargs)
    
    def get_store(self, store_id: str) -> Optional[MeijerStore]:
        """Get specific store details."""
        return self.store_search.get_store_details(store_id)
    
    def find_all_stores(self, **kwargs) -> List[MeijerStore]:
        """Get all Meijer stores."""
        return self.store_search.get_all_stores(**kwargs)


if __name__ == "__main__":
    # Example usage
    store_search = MeijerStoreSearch()
    
    # Find stores near a location (coordinates from analysis)
    stores = store_search.find_stores_nearby(
        latitude=42.82893, 
        longitude=-86.09048,
        radius_miles=50,
        max_results=10
    )
    
    print(f"Found {len(stores)} stores:")
    for store in stores:
        print(f"  - {store}")
    
    # Get specific store details (ID from analysis)
    store_217 = store_search.get_store_details("217")
    if store_217:
        print(f"\\nStore 217 details:")
        print(f"  Name: {store_217.display_name}")
        print(f"  Address: {store_217.full_address}")
        print(f"  Services: {store_217.get_store_services()}")
'''

        return search_function

    def generate_report(self) -> Dict[str, Any]:
        """Generate comprehensive analysis report."""
        return {
            "summary": {
                "total_flows_analyzed": len(self.flows),
                "store_info_proximity_calls": len(self.analysis.proximity_calls),
                "store_info_specific_calls": len(self.analysis.specific_store_calls),
                "unique_store_fields": len(self.analysis.unique_store_fields),
                "total_stores_analyzed": len(self.analysis.store_structures),
                "unique_store_ids": len(self.analysis.store_ids_found),
                "unique_search_locations": len(self.analysis.coordinates),
            },
            "api_endpoints": dict(self.analysis.api_endpoints),
            "discovered_store_ids": self.analysis.store_ids_found,
            "search_locations": self.analysis.coordinates,
            "api_parameters": {
                k: dict(v.most_common(5))
                for k, v in self.analysis.api_parameters.items()
            },
            "store_field_analysis": {
                "most_common_fields": dict(
                    self.analysis.unique_store_fields.most_common(30)
                ),
                "field_data_types": self.analysis.field_data_types,
            },
            "sample_stores": self.analysis.store_structures[:3]
            if self.analysis.store_structures
            else [],
            "endpoint_patterns": {
                "proximity_search": "/digital/storeInfo/v2/stores/proximity",
                "specific_store": "/digital/storeInfo/stores/{storeId}",
            },
        }

    def save_report(self, output_file: str = "store_info_analysis.json") -> None:
        """Save the analysis report to a JSON file."""
        try:
            report = self.generate_report()

            with open(output_file, "w") as f:
                json.dump(report, f, indent=2, default=str)

            self.logger.info(f"StoreInfo analysis report saved to: {output_file}")

        except Exception as e:
            self.logger.error(f"Error saving report: {e}")

    def save_meijer_store_class(self, output_file: str = "meijer_store.py") -> None:
        """Save the generated MeijerStore class to a Python file."""
        try:
            class_definition = self.generate_meijer_store_class()

            with open(output_file, "w") as f:
                f.write(class_definition)

            self.logger.info(f"MeijerStore class saved to: {output_file}")

        except Exception as e:
            self.logger.error(f"Error saving MeijerStore class: {e}")

    def save_store_search_function(
        self, output_file: str = "meijer_store_search.py"
    ) -> None:
        """Save the generated store search function to a Python file."""
        try:
            search_function = self.generate_store_search_function()

            with open(output_file, "w") as f:
                f.write(search_function)

            self.logger.info(f"Meijer store search function saved to: {output_file}")

        except Exception as e:
            self.logger.error(f"Error saving store search function: {e}")

    def print_summary(self) -> None:
        """Print a summary of the storeInfo analysis."""
        report = self.generate_report()
        summary = report["summary"]

        print("\n" + "=" * 80)
        print("🏪 STORE INFO API ANALYSIS SUMMARY")
        print("=" * 80)

        print(f"📊 Total Flows Analyzed: {summary['total_flows_analyzed']:,}")
        print(f"🔍 Proximity Search Calls: {summary['store_info_proximity_calls']:,}")
        print(f"🏪 Specific Store Calls: {summary['store_info_specific_calls']:,}")
        print(f"🏷️  Stores Analyzed: {summary['total_stores_analyzed']:,}")
        print(f"🔑 Unique Store Fields: {summary['unique_store_fields']:,}")
        print(f"🏬 Unique Store IDs: {summary['unique_store_ids']:,}")
        print(f"📍 Search Locations: {summary['unique_search_locations']:,}")

        print("\n🔧 API Endpoints:")
        for endpoint, count in report["api_endpoints"].items():
            print(f"   {endpoint}: {count} calls")

        print("\n🏪 Discovered Store IDs:")
        store_ids = report["discovered_store_ids"][:10]  # Show first 10
        print(f"   {', '.join(store_ids)}")
        if len(report["discovered_store_ids"]) > 10:
            print(f"   ... and {len(report['discovered_store_ids']) - 10} more")

        print("\n📍 Search Locations (sample):")
        for i, coord in enumerate(report["search_locations"][:5], 1):
            print(
                f"   {i}. ({coord['latitude']}, {coord['longitude']}) - {coord['miles']} miles, {coord['numToReturn']} results"
            )

        print("\n🏷️  Most Common Store Fields:")
        for field, count in list(
            report["store_field_analysis"]["most_common_fields"].items()
        )[:15]:
            field_type = report["store_field_analysis"]["field_data_types"].get(
                field, "Unknown"
            )
            print(f"   {field} ({field_type}): appears in {count} stores")

        print("\n" + "=" * 80)


def main():
    """Main function to analyze storeInfo endpoints in meijer2.log."""
    print("🏪 StoreInfo API Analyzer")
    print("=" * 60)

    # Initialize analyzer with meijer2.log
    analyzer = StoreInfoAnalyzer("meijer2.log")

    # Load flows
    print("📂 Loading flows from meijer2.log...")
    if not analyzer.load_flows():
        print("❌ Failed to load flows. Exiting.")
        return

    # Analyze storeInfo flows
    print("🔍 Analyzing storeInfo flows...")
    analyzer.analyze_store_info_flows()

    # Generate and display report
    print("📊 Generating storeInfo analysis report...")
    analyzer.print_summary()

    # Save detailed report
    print("💾 Saving detailed analysis report...")
    analyzer.save_report()

    # Generate and save MeijerStore class
    print("🏗️  Generating MeijerStore class...")
    analyzer.save_meijer_store_class()

    # Generate and save store search function
    print("🔍 Generating Meijer store search function...")
    analyzer.save_store_search_function()

    print("\n✅ StoreInfo analysis completed successfully!")
    print("📄 Check 'store_info_analysis.json' for detailed results")
    print("🐍 Check 'meijer_store.py' for the generated MeijerStore class")
    print("🔍 Check 'meijer_store_search.py' for the store search functionality")


if __name__ == "__main__":
    main()
