"""
Meijer API Client Package
========================

A comprehensive Python client for the Meijer mobile app API.

Features:
- Unified authentication (Bearer tokens, OAuth, Selenium)
- Complete Shop & Scan functionality
- Shopping lists, coupons, store search
- Automatic token management and refresh
- Clean simplified API

Usage:
    from meijer import Meijer

    # Simple auto-discovery authentication
    client = Meijer()

    # With custom auth file
    client = Meijer(auth="auth.txt")
"""

# Core exports
from .exceptions import (
    MeijerError,
    MeijerAuthenticationError,
    MeijerAPIError,
    MeijerRateLimitError,
)

from .models import (
    AuthTokens,
    UserInfo,
    ShopScanItem,
    ShopScanTrip,
    ListItem,
    MeijerOffer,
    MeijerStore,
    OAuthConfig,
)

from .enums import AuthenticationStatus, HatColor, BorderColor

from .auth import MeijerAuth, TokenStorage, load_auth_from_config_file, load_auth_file

__version__ = "1.0.0"
__author__ = "Generated by Claude Sonnet 4"

# Main client
from .client import Meijer

__all__ = [
    # Exceptions
    "MeijerError",
    "MeijerAuthenticationError",
    "MeijerAPIError",
    "MeijerRateLimitError",
    # Models
    "AuthTokens",
    "UserInfo",
    "ShopScanItem",
    "ShopScanTrip",
    "ListItem",
    "MeijerOffer",
    "MeijerStore",
    "OAuthConfig",
    # Enums
    "AuthenticationStatus",
    "HatColor",
    "BorderColor",
    # Auth
    "MeijerAuth",
    "TokenStorage",
    "load_auth_from_config_file",
    "load_auth_file",
    # Main client
    "Meijer",
]
