# -*- coding: utf-8 -*-
# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ""

setup(
    long_description=readme,
    name="meijer",
    version="0.0.2",
    description="Reverse engineered API for Meijer apps & services.",
    python_requires="==3.*,>=3.8.0",
    author="jed",
    author_email="jed@bored",
    entry_points={"console_scripts": ["meijer = meijer:cli"]},
    packages=["meijer"],
    package_dir={"": "."},
    package_data={},
    install_requires=["cached-property==1.*,>=1.5.0", "requests==2.*,>=2.22.0"],
    extras_require={"dev": ["pytest==3.*,>=3.0.0"]},
)
