#Fullstory Config
#Fri Aug 15 14:57:03 UTC 2025
com.fullstory.API_TRACE_ENABLED=false
com.fullstory.APP_SERVER=https\://app.fullstory.com
com.fullstory.ASYNC_ENABLED=true
com.fullstory.BUG_REPORTING_ENABLED=true
com.fullstory.BUILD_ID=feb20e90-fcbb-4d35-b580-00a54719f289
com.fullstory.COMPOSE_RUNTIME_VERSION=1.8.3
com.fullstory.COMPOSE_SELECTOR_VERSION=5
com.fullstory.COMPOSE_SUPPORT=true
com.fullstory.COMPOSE_UI_VERSION=1.8.3
com.fullstory.DISABLE_FORCED_ACCESSIBILITY=false
com.fullstory.FRAGMENT_SUPPORT=true
com.fullstory.IGNORE_PROCESS_CHECK=false
com.fullstory.LOGCAT_LEVEL=info
com.fullstory.LOG_LEVEL=info
com.fullstory.LOTTIE_SUPPORT=true
com.fullstory.MASK_ASSETS=false
com.fullstory.MAX_API=36
com.fullstory.MIN_API=24
com.fullstory.OKHTTP_SUPPORT=true
com.fullstory.ORG=10QQJ9
com.fullstory.PLUGIN_VERSION=1.62.2
com.fullstory.PREVIEW_MODE_ENABLED=false
com.fullstory.PROTOCOL_VERSION=1755199766
com.fullstory.RECORDER=https\://mr.fullstory.com
com.fullstory.RECORD_ON_START=false
com.fullstory.SERVER=https\://fullstory.com
com.fullstory.URLCONNECTION_SUPPORT=true
com.fullstory.USE_PROXY_SERVER=false
com.fullstory.VERBOSE_LOGGING=true
com.fullstory.WEBVIEW_INJECTION=true
com.fullstory.WEBVIEW_NAMESPACE=FS
