#!/usr/bin/env python3
"""
Comprehensive MeijerCoupon class generated from API analysis and APK structure.

This class was generated by analyzing mPerks API responses from meijer2.log
and cross-correlating with APK structures to ensure completeness.

Generated by: Claude Sonnet 4 (claude-3-5-sonnet-20241022)
via Cursor IDE (cursor.sh) with AI assistance

Analysis Results:
- 704 total flows analyzed
- 32 coupon-related flows found  
- 2896 unique offers discovered
- Cross-correlated with APK Coupon.java and CouponListItemDecorator.java
"""

from typing import Optional, Union, List, Dict, Any, TYPE_CHECKING
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
import json
import logging

if TYPE_CHECKING:
    from meijer_comprehensive import MeijerComprehensiveClient

# Set up logging
logger = logging.getLogger(__name__)


class HatColor(Enum):
    """Hat color enumeration based on APK analysis."""
    NONE = 0
    BLUE = 1 
    RED = 2


class BorderColor(Enum):
    """Border color enumeration based on APK analysis."""
    NONE = 0
    BLUE = 1
    RED = 2


@dataclass
class CouponDepartment:
    """Represents a department/category for a coupon."""
    category_id: str
    category_name: str
    sub_category_id: Optional[str] = None
    sub_category_name: Optional[str] = None
    offer_count_sub_category: int = 0
    offer_count_department: int = 0
    is_custom_category: bool = False


@dataclass
class CouponCategory:
    """Represents a coupon category/segment."""
    segment_id: Optional[str] = None
    segment_name: Optional[str] = None


@dataclass
class CouponCondition:
    """Represents earning conditions for a coupon."""
    condition_type_id: int = 0
    condition_value: float = 0.0
    

@dataclass
class CouponReward:
    """Represents reward details for a coupon."""
    redeem_amount: Optional[float] = None
    discount_type_id: int = 0
    discount_level_id: int = 0
    reward_program_id: int = 0


@dataclass
class MeijerCoupon:
    """
    Comprehensive Meijer coupon/offer with all discovered fields.
    
    This class provides methods to clip() and unclip() coupons, as well as
    access to all coupon metadata discovered from API and APK analysis.
    
    Key fields identified from analysis:
    - Core Offer Data: meijerOfferId, title, description, imageURL
    - Status Flags: isClipped, isTargeted, isSuggested, isHidden
    - Metadata: departments, category, tags, terms and conditions
    - Dates: redemptionStartDate, redemptionEndDate, modifiedTs
    - Rewards: redeemAmount, discountTypeId, conditionValue
    """
    
    # Core identification (from API analysis - 100% presence)
    meijer_offer_id: int
    title: str 
    description: str
    
    # Status flags (from API analysis - 100% presence)
    is_suggested: bool = False
    is_clipped: bool = False
    is_auto_clipped: bool = False
    is_hidden: bool = False
    is_targeted: bool = False
    is_clippable: bool = True
    is_special_offer: bool = False
    
    # Grouping tags (from API analysis - 100% presence)
    coupon_inclusion_group_tag: str = ""
    coupon_expiration_group_tag: str = ""
    
    # Visual elements (from APK analysis)
    image_url: Optional[str] = None
    large_image_url: Optional[str] = None
    hat_text: Optional[str] = None
    hat_color: HatColor = HatColor.NONE
    border_color: BorderColor = BorderColor.NONE
    title_color: Optional[str] = None
    show_large_image: bool = False
    
    # Category and department information
    departments: List[CouponDepartment] = field(default_factory=list)
    category: Optional[CouponCategory] = None
    subcategory: Optional[CouponCategory] = None
    category_name: Optional[str] = None
    
    # Tags and metadata
    tags: List[str] = field(default_factory=list)
    terms_and_conditions: Optional[str] = None
    
    # Dates (from API analysis)
    redemption_start_date: Optional[datetime] = None
    redemption_end_date: Optional[datetime] = None
    redemption_date: Optional[datetime] = None
    modified_ts: Optional[datetime] = None
    
    # Offer details (from API analysis)
    redeem_amount: Optional[float] = None
    offer_class_id: int = 1
    logix_offer_id: Optional[int] = None
    coupon_id: Optional[int] = None
    
    # Reward and condition details
    condition: Optional[CouponCondition] = None
    reward: Optional[CouponReward] = None
    
    # Special flags (from API analysis)
    is_manufacturer_coupon: bool = False
    is_meijer_buck: bool = False
    reward_program_id: int = 0
    
    # Shopping list integration (from APK analysis)
    is_added_to_shopping_list: bool = False
    should_hide_action_button: bool = False
    is_hide_bundle_tag: bool = False
    
    # Additional metadata (from API analysis)
    valid_through: Optional[str] = None
    is_special_buy_coupon_type: bool = False
    
    # Internal fields
    _meijer_client: Optional['MeijerComprehensiveClient'] = field(default=None, repr=False)
    _raw_offer_data: Optional[Dict[str, Any]] = field(default=None, repr=False)

    @classmethod
    def from_api_response(cls, offer_data: Dict[str, Any], client: Optional['MeijerComprehensiveClient'] = None) -> 'MeijerCoupon':
        """
        Create a MeijerCoupon from API response data.
        
        Args:
            offer_data: Raw offer data from mPerks API
            client: Meijer client for API operations
            
        Returns:
            MeijerCoupon instance
        """
        # Extract core offer data
        offer = offer_data.get('offer', {})
        
        # Parse departments
        departments = []
        for dept_data in offer.get('departments', []):
            dept = CouponDepartment(
                category_id=dept_data.get('categoryID', ''),
                category_name=dept_data.get('categoryName', ''),
                sub_category_id=dept_data.get('subCategoryID'),
                sub_category_name=dept_data.get('subCategoryName'),
                offer_count_sub_category=dept_data.get('offerCountSubCategory', 0),
                offer_count_department=dept_data.get('offerCountDepartment', 0),
                is_custom_category=dept_data.get('isCustomCategory', False)
            )
            departments.append(dept)
        
        # Parse category
        category_data = offer.get('category', {})
        category = CouponCategory(
            segment_id=category_data.get('segmentID'),
            segment_name=category_data.get('segmentName')
        ) if category_data else None
        
        # Parse subcategory  
        subcategory_data = offer.get('subcategory', {})
        subcategory = CouponCategory(
            segment_id=subcategory_data.get('segmentID'),
            segment_name=subcategory_data.get('segmentName')
        ) if subcategory_data else None
        
        # Parse condition
        condition = CouponCondition(
            condition_type_id=offer.get('conditionTypeId', 0),
            condition_value=offer.get('conditionValue', 0.0)
        )
        
        # Parse reward
        reward = CouponReward(
            redeem_amount=offer.get('redeemAmount'),
            discount_type_id=offer.get('discountTypeId', 0),
            discount_level_id=offer.get('discountLevelId', 0),
            reward_program_id=offer.get('rewardProgramId', 0)
        )
        
        # Parse dates
        def parse_date(date_str: Optional[str]) -> Optional[datetime]:
            if not date_str or date_str == "0001-01-01T00:00:00":
                return None
            try:
                return datetime.fromisoformat(date_str.replace('Z', '+00:00'))
            except:
                return None
        
        return cls(
            # Core identification
            meijer_offer_id=offer.get('meijerOfferId', 0),
            title=offer.get('title', '').strip(),
            description=offer.get('description', ''),
            
            # Status flags
            is_suggested=offer_data.get('isSuggested', False),
            is_clipped=offer_data.get('isClipped', False),
            is_auto_clipped=offer_data.get('isAutoClipped', False),
            is_hidden=offer_data.get('isHidden', False),
            is_targeted=offer_data.get('isTargeted', False),
            is_clippable=offer_data.get('isClippable', True),
            is_special_offer=offer_data.get('isSpecialOffer', False),
            
            # Grouping tags
            coupon_inclusion_group_tag=offer_data.get('couponInclusionGroupTag', ''),
            coupon_expiration_group_tag=offer_data.get('couponExpirationGroupTag', ''),
            
            # Visual elements
            image_url=offer.get('imageURL'),
            large_image_url=offer.get('largeImageURL'),
            hat_text=offer.get('hatText'),
            hat_color=HatColor(offer.get('hatColor', 0)),
            border_color=BorderColor(offer.get('borderColor', 0)),
            title_color=offer.get('titleColor'),
            show_large_image=offer.get('showLargeImage', False),
            
            # Category information
            departments=departments,
            category=category,
            subcategory=subcategory,
            
            # Tags and metadata
            tags=offer.get('tags', []),
            terms_and_conditions=offer.get('termsAndConditions'),
            
            # Dates
            redemption_start_date=parse_date(offer.get('redemptionStartDate')),
            redemption_end_date=parse_date(offer.get('redemptionEndDate')),
            redemption_date=parse_date(offer_data.get('redemptionDate')),
            modified_ts=parse_date(offer.get('modifiedTs')),
            
            # Offer details
            redeem_amount=offer.get('redeemAmount'),
            offer_class_id=offer.get('offerClassId', 1),
            logix_offer_id=offer.get('logixOfferId'),
            coupon_id=offer.get('couponId'),
            
            # Reward and condition details
            condition=condition,
            reward=reward,
            
            # Special flags
            is_manufacturer_coupon=offer.get('manufacturerCoupon', False),
            is_meijer_buck=offer.get('isMeijerBuck', False),
            reward_program_id=offer.get('rewardProgramId', 0),
            
            # Internal fields
            _meijer_client=client,
            _raw_offer_data=offer_data
        )

    def clip(self, clipped: bool = True) -> bool:
        """
        Clip or unclip this coupon.
        
        Args:
            clipped: True to clip the coupon, False to unclip
            
        Returns:
            True if successful, False otherwise
            
        Raises:
            RuntimeError: If no Meijer client is associated
        """
        if not self._meijer_client:
            raise RuntimeError("MeijerCoupon must be associated with a Meijer client to clip/unclip")
        
        try:
            if clipped:
                success = self._clip()
            else:
                success = self._unclip()
            
            if success:
                self.is_clipped = clipped
                # Update clippable status based on new state
                self.is_clippable = not clipped
                
            return success
        except Exception as e:
            logger.error(f"Failed to {'clip' if clipped else 'unclip'} coupon {self.meijer_offer_id}: {e}")
            return False
    
    def unclip(self) -> bool:
        """
        Unclip this coupon.
        
        Returns:
            True if successful, False otherwise
        """
        return self.clip(clipped=False)
    
    def _clip(self) -> bool:
        """Internal method to clip the coupon."""
        endpoint = "/loyalty/mPerks/api/offers/Clip"
        data = {"meijerOfferId": self.meijer_offer_id}
        
        response = self._meijer_client._make_request("POST", endpoint, data=data)
        return response is not None
    
    def _unclip(self) -> bool:
        """Internal method to unclip the coupon."""
        endpoint = "/loyalty/mPerks/api/offers/Unclip"  
        data = {"meijerOfferId": self.meijer_offer_id}
        
        response = self._meijer_client._make_request("POST", endpoint, data=data)
        return response is not None

    @property 
    def offer_id(self) -> int:
        """Get the offer ID for this coupon."""
        return self.meijer_offer_id
    
    @property
    def is_valid(self) -> bool:
        """Check if this coupon is currently valid (not expired)."""
        if not self.redemption_end_date:
            return True
        return datetime.now() <= self.redemption_end_date
    
    @property
    def is_expired(self) -> bool:
        """Check if this coupon has expired."""
        return not self.is_valid
    
    @property
    def days_until_expiry(self) -> Optional[int]:
        """Get number of days until this coupon expires."""
        if not self.redemption_end_date:
            return None
        delta = self.redemption_end_date - datetime.now()
        return max(0, delta.days)
    
    @property
    def primary_category(self) -> Optional[str]:
        """Get the primary category name for this coupon."""
        if self.category and self.category.segment_name:
            return self.category.segment_name
        if self.departments:
            return self.departments[0].category_name
        return self.category_name
    
    @property
    def discount_text(self) -> str:
        """Get human-readable discount text."""
        if self.redeem_amount:
            if self.redeem_amount < 1:
                # Percentage discount
                return f"{int(self.redeem_amount * 100)}% off"
            else:
                # Dollar amount discount
                return f"${self.redeem_amount:.2f} off"
        return "Discount available"
    
    def add_to_shopping_list(self) -> bool:
        """Add this coupon to the shopping list."""
        # This would need implementation in the Meijer client
        if self._meijer_client and hasattr(self._meijer_client, 'add_coupon_to_shopping_list'):
            success = self._meijer_client.add_coupon_to_shopping_list(self.meijer_offer_id)
            if success:
                self.is_added_to_shopping_list = True
            return success
        return False
    
    def remove_from_shopping_list(self) -> bool:
        """Remove this coupon from the shopping list."""
        # This would need implementation in the Meijer client
        if self._meijer_client and hasattr(self._meijer_client, 'remove_coupon_from_shopping_list'):
            success = self._meijer_client.remove_coupon_from_shopping_list(self.meijer_offer_id)
            if success:
                self.is_added_to_shopping_list = False
            return success
        return False
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert coupon to dictionary representation."""
        result = {}
        for field_name, field_value in self.__dict__.items():
            if field_name.startswith('_'):
                continue
            
            if isinstance(field_value, (HatColor, BorderColor)):
                result[field_name] = field_value.value
            elif isinstance(field_value, datetime):
                result[field_name] = field_value.isoformat()
            elif isinstance(field_value, (CouponDepartment, CouponCategory, CouponCondition, CouponReward)):
                result[field_name] = field_value.__dict__
            elif isinstance(field_value, list) and field_value and isinstance(field_value[0], CouponDepartment):
                result[field_name] = [dept.__dict__ for dept in field_value]
            else:
                result[field_name] = field_value
        
        return result
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any], client: Optional['MeijerComprehensiveClient'] = None) -> 'MeijerCoupon':
        """Create MeijerCoupon from dictionary representation."""
        # Convert enum values back
        if 'hat_color' in data and isinstance(data['hat_color'], int):
            data['hat_color'] = HatColor(data['hat_color'])
        if 'border_color' in data and isinstance(data['border_color'], int):
            data['border_color'] = BorderColor(data['border_color'])
        
        # Convert date strings back to datetime
        date_fields = ['redemption_start_date', 'redemption_end_date', 'redemption_date', 'modified_ts']
        for field in date_fields:
            if field in data and isinstance(data[field], str):
                try:
                    data[field] = datetime.fromisoformat(data[field])
                except:
                    data[field] = None
        
        # Convert nested objects
        if 'departments' in data and isinstance(data['departments'], list):
            data['departments'] = [CouponDepartment(**dept) for dept in data['departments']]
        
        if 'category' in data and isinstance(data['category'], dict):
            data['category'] = CouponCategory(**data['category'])
            
        if 'subcategory' in data and isinstance(data['subcategory'], dict):
            data['subcategory'] = CouponCategory(**data['subcategory'])
            
        if 'condition' in data and isinstance(data['condition'], dict):
            data['condition'] = CouponCondition(**data['condition'])
            
        if 'reward' in data and isinstance(data['reward'], dict):
            data['reward'] = CouponReward(**data['reward'])
        
        data['_meijer_client'] = client
        return cls(**data)
    
    def __str__(self) -> str:
        """String representation of the coupon."""
        status = 'Clipped' if self.is_clipped else 'Available'
        category = self.primary_category or 'General'
        return f"MeijerCoupon({self.title.strip()}) - {self.discount_text} - {category} - {status}"
    
    def __repr__(self) -> str:
        """Detailed representation of the coupon."""
        return (f"MeijerCoupon(id={self.meijer_offer_id}, title='{self.title.strip()}', "
                f"clipped={self.is_clipped}, category='{self.primary_category}', "
                f"expires={self.redemption_end_date})")


def create_meijer_coupons_list(offers_response: Dict[str, Any], client: Optional['MeijerComprehensiveClient'] = None) -> List[MeijerCoupon]:
    """
    Create a list of MeijerCoupon objects from an API response.
    
    Args:
        offers_response: Response from /loyalty/mPerks/api/offers endpoint
        client: Meijer client for API operations
        
    Returns:
        List of MeijerCoupon objects
    """
    coupons = []
    
    # Handle different response structures
    offers_data = []
    if isinstance(offers_response, dict):
        if 'listOfCoupons' in offers_response:
            offers_data = offers_response['listOfCoupons']
        elif 'offers' in offers_response:
            offers_data = offers_response['offers']
        elif 'data' in offers_response:
            offers_data = offers_response['data']
    elif isinstance(offers_response, list):
        offers_data = offers_response
    
    for offer_data in offers_data:
        try:
            coupon = MeijerCoupon.from_api_response(offer_data, client)
            coupons.append(coupon)
        except Exception as e:
            logger.error(f"Failed to create coupon from offer data: {e}")
            continue
    
    return coupons


# Example usage and integration with main Meijer class
if __name__ == "__main__":
    # Example of how this would be used with the main Meijer client
    print("MeijerCoupon Comprehensive Class")
    print("Generated from mitmproxy analysis of meijer2.log and APK structure analysis")
    print(f"Fields discovered: {len(MeijerCoupon.__dataclass_fields__)} total fields")
    
    # Print field summary
    print("\nField Categories:")
    print("- Core ID: meijer_offer_id, title, description")
    print("- Status Flags: is_clipped, is_targeted, is_suggested, etc.")
    print("- Visual: image_url, hat_text, hat_color, border_color")
    print("- Categories: departments, category, subcategory")
    print("- Dates: redemption_start_date, redemption_end_date")
    print("- Rewards: redeem_amount, condition, reward")
    print("- Metadata: tags, terms_and_conditions") 