#!/usr/bin/env python3
"""
MeijerCoupon class generated from API analysis.

This class was automatically generated by analyzing mPerks API responses
and APK structures to understand the complete coupon data model.
"""

from typing import Optional, Union, List, Dict, Any
from dataclasses import dataclass, field
from datetime import datetime
import requests
import json


@dataclass
class MeijerCoupon:
    """
    Represents a Meijer coupon/offer with all discovered fields.

    This class provides methods to clip() and unclip() coupons, as well as
    access to all coupon metadata discovered from API analysis.
    """

    offer: dict
    is_suggested: bool
    is_clipped: bool
    is_auto_clipped: bool
    is_hidden: bool
    is_targeted: bool
    coupon_inclusion_group_tag: str
    coupon_expiration_group_tag: str
    is_clippable: bool
    is_special_offer: bool
    redemption_date: NoneType

    # Internal fields
    _meijer_client: Optional[Any] = field(default=None, repr=False)

    def clip(self, clipped: bool = True) -> bool:
        """
        Clip or unclip this coupon.

        Args:
            clipped: True to clip the coupon, False to unclip

        Returns:
            True if successful, False otherwise
        """
        if not self._meijer_client:
            raise RuntimeError(
                "MeijerCoupon must be associated with a Meijer client to clip/unclip"
            )

        try:
            if clipped:
                return self._clip()
            else:
                return self._unclip()
        except Exception:
            return False

    def unclip(self) -> bool:
        """
        Unclip this coupon.

        Returns:
            True if successful, False otherwise
        """
        return self.clip(clipped=False)

    def _clip(self) -> bool:
        """Internal method to clip the coupon."""
        offer_id = getattr(self, "meijer_offer_id", None) or getattr(
            self, "offer_id", None
        )
        if not offer_id:
            return False

        endpoint = "/loyalty/mPerks/api/offers/Clip"
        data = {"meijerOfferId": offer_id}

        response = self._meijer_client._make_request("POST", endpoint, data=data)
        return response is not None

    def _unclip(self) -> bool:
        """Internal method to unclip the coupon."""
        offer_id = getattr(self, "meijer_offer_id", None) or getattr(
            self, "offer_id", None
        )
        if not offer_id:
            return False

        endpoint = "/loyalty/mPerks/api/offers/Unclip"
        data = {"meijerOfferId": offer_id}

        response = self._meijer_client._make_request("POST", endpoint, data=data)
        return response is not None

    @property
    def is_clipped(self) -> bool:
        """Check if this coupon is currently clipped."""
        return getattr(self, "clipped", False) or getattr(self, "is_clipped", False)

    @property
    def offer_id(self) -> Optional[str]:
        """Get the offer ID for this coupon."""
        return (
            getattr(self, "meijer_offer_id", None)
            or getattr(self, "offer_id", None)
            or getattr(self, "id", None)
        )

    def __str__(self) -> str:
        """String representation of the coupon."""
        title = (
            getattr(self, "title", None)
            or getattr(self, "name", None)
            or "Unknown Coupon"
        )
        status = "Clipped" if self.is_clipped else "Available"
        return f"MeijerCoupon({title}) - {status}"
