package com.google.zxing;

/* loaded from: classes7.dex */
public enum n {
    OTHER,
    ORIENTATION,
    BYTE_SEGMENTS,
    ERROR_CORRECTION_LEVEL,
    ERRORS_CORRECTED,
    ERASURES_CORRECTED,
    ISSUE_NUMBER,
    SUGGESTED_PRICE,
    POSSIBLE_COUNTRY,
    UPC_EAN_EXTENSION,
    PDF417_EXTRA_METADATA,
    STRUCTURED_APPEND_SEQUENCE,
    STRUCTURED_APPEND_PARITY,
    SYMBOLOGY_IDENTIFIER
}
