# Bash completion functionality for Meijer API Client
# Command completion and installation

.PHONY: completion
completion:
	@echo "🔧 Installing bash completion for make targets..."
	@echo ""
	@echo "📝 Add this to your ~/.bashrc or ~/.bash_profile:"
	@echo "  source <(make completion-bash)"
	@echo ""
	@echo "💡 Or run this command to install it:"
	@echo "  make completion-install"

.PHONY: completion-bash
completion-bash:
	@echo "# Meijer API Client Makefile Bash Completion"
	@echo "# Generated by 'make completion-bash'"
	@echo ""
	@echo "_meijer_make_completion() {"
	@echo "    local cur prev opts"
	@echo "    COMPREPLY=()"
	@echo "    cur=\"\$${COMP_WORDS[COMP_CWORD]}\""
	@echo "    prev=\"\$${COMP_WORDS[COMP_CWORD-1]}\""
	@echo ""
	@echo "    # Main make targets"
	@echo "    if [ \$${COMP_CWORD} -eq 1 ]; then"
	@echo "        opts=\"help venv notebook regenerate-notebooks execute-notebooks notebook-workflow demos log logs rotate-logs auth clean completion completion-bash completion-install version version-tag\""
	@echo "        COMPREPLY=( \$$(compgen -W \"\$$opts\" -- \$$cur) )"
	@echo "        return 0"
	@echo "    fi"
	@echo ""
	@echo "    # Handle FILE= parameter for auth target"
	@echo "    if [ \"\$$prev\" = \"auth\" ] || [ \"\$$prev\" = \"FILE=\" ]; then"
	@echo "        # Complete log files"
	@echo "        local log_files=\$$(ls logs/meijer_mitm_*.log 2>/dev/null | sed 's/^/FILE=/' 2>/dev/null || echo \"\")"
	@echo "        if [ -n \"\$$log_files\" ]; then"
	@echo "            COMPREPLY=( \$$(compgen -W \"\$$log_files\" -- \$$cur) )"
	@echo "        fi"
	@echo "        return 0"
	@echo "    fi"
	@echo ""
	@echo "    # Handle VENV= parameter for venv target"
	@echo "    if [ \"\$$prev\" = \"venv\" ] || [ \"\$$prev\" = \"VENV=\" ]; then"
	@echo "        COMPREPLY=( \$$(compgen -W \"venv venv2 venv3\" -- \$$cur) )"
	@echo "        return 0"
	@echo "    fi"
	@echo "}"
	@echo ""
	@echo "complete -F _meijer_make_completion make"

.PHONY: completion-install
completion-install:
	@echo "🔧 Installing bash completion for Meijer API Client..."
	@if [ -f ~/.bashrc ]; then \
		echo "" >> ~/.bashrc; \
		echo "# Meijer API Client bash completion" >> ~/.bashrc; \
		echo "source <(cd /projects/python_Meijer && make completion-bash)" >> ~/.bashrc; \
		echo "✅ Added to ~/.bashrc"; \
		echo "🔄 Run 'source ~/.bashrc' or start a new terminal to activate"; \
	elif [ -f ~/.bash_profile ]; then \
		echo "" >> ~/.bash_profile; \
		echo "# Meijer API Client bash completion" >> ~/.bash_profile; \
		echo "source <(cd /projects/python_Meijer && make completion-bash)" >> ~/.bash_profile; \
		echo "✅ Added to ~/.bash_profile"; \
		echo "🔄 Run 'source ~/.bash_profile' or start a new terminal to activate"; \
	else \
		echo "❌ No ~/.bashrc or ~/.bash_profile found"; \
		echo "💡 Create one of these files or manually add the completion source"; \
	fi

.PHONY: completion-test
completion-test:
	@echo "🧪 Testing bash completion..."
	@echo "💡 In a new terminal, try:"
	@echo "   make <TAB>                    # Should show all targets"
	@echo "   make auth FILE=<TAB>          # Should complete log files"
	@echo "   make venv VENV=<TAB>          # Should complete venv names"
	@echo ""
	@echo "🔧 If completion doesn't work, run:"
	@echo "   make completion-install"
	@echo "   source ~/.bashrc"
