# Bash Completion Sub-Makefile
# Contains targets for bash completion installation and testing

.PHONY: completion
completion:
	@echo "🔧 Installing bash completion for make targets..."
	@echo ""
	@echo "📝 Add this to your ~/.bashrc or ~/.bash_profile:"
	@echo "  source <(make completion-bash)"
	@echo ""
	@echo "💡 Or run this command to install it:"
	@echo "  make completion-install"

.PHONY: completion-bash
completion-bash:
	@echo "# Meijer API Client Makefile Bash Completion"
	@echo "# Generated by 'make completion-bash'"
	@echo ""
	@echo "_meijer_make_completion() {"
	@echo "    local cur prev opts"
	@echo "    COMPREPLY=()"
	@echo "    cur=\"\$${COMP_WORDS[COMP_CWORD]}\""
	@echo "    prev=\"\$${COMP_WORDS[COMP_CWORD-1]}\""
	@echo ""
	@echo "    # Main make targets"
	@echo "    if [ \$${COMP_CWORD} -eq 1 ]; then"
	@echo "        opts=\"help venv notebook notebooks-gen notebooks-execute notebooks-gen-execute demos log logs auth clean completion completion-bash completion-install\""
	@echo "        COMPREPLY=( \$$(compgen -W \"\$$opts\" -- \$$cur) )"
	@echo "        return 0"
	@echo "    fi"
	@echo ""

	@echo ""
	@echo "    # Handle VENV= parameter for venv target"
	@echo "    if [ \"\$$prev\" = \"venv\" ] || [ \"\$$prev\" = \"VENV=\" ]; then"
	@echo "        COMPREPLY=( \$$(compgen -W \"venv venv2 venv3\" -- \$$cur) )"
	@echo "        return 0"
	@echo "    fi"
	@echo "}"
	@echo ""
	@echo "complete -F _meijer_make_completion make"

.PHONY: completion-install
completion-install:
	@echo "🔧 Installing bash completion for Meijer API Client..."
	@echo "📝 Add this line to your ~/.bashrc or ~/.bash_profile:"
	@echo "   source <(cd /projects/python_Meijer && make completion-bash)"
	@echo ""
	@echo "💡 Then run 'source ~/.bashrc' or start a new terminal to activate"

.PHONY: completion-test
completion-test:
	@echo "🧪 Testing bash completion..."
	@echo "💡 In a new terminal, try:"
	@echo "   make <TAB>                    # Should show all targets"
	@echo "   make auth                     # Should complete auth target"
	@echo "   make venv VENV=<TAB>          # Should complete venv names"
	@echo ""
	@echo "🔧 If completion doesn't work, run:"
	@echo "   make completion-install"
	@echo "   source ~/.bashrc"
