package Dd;

import com.radiusnetworks.flybuy.api.network.response.HttpResponseStatus;

/* loaded from: classes6.dex */
public enum Y6 implements O0 {
    NO_ERROR(0),
    INCOMPATIBLE_INPUT(1),
    INCOMPATIBLE_OUTPUT(2),
    INCOMPATIBLE_TFLITE_VERSION(3),
    MISSING_OP(4),
    DATA_TYPE_ERROR(6),
    TFLITE_INTERNAL_ERROR(7),
    TFLITE_UNKNOWN_ERROR(8),
    MEDIAPIPE_ERROR(9),
    TIME_OUT_FETCHING_MODEL_METADATA(5),
    MODEL_NOT_DOWNLOADED(100),
    URI_EXPIRED(101),
    NO_NETWORK_CONNECTION(102),
    METERED_NETWORK(103),
    DOWNLOAD_FAILED(104),
    MODEL_INFO_DOWNLOAD_UNSUCCESSFUL_HTTP_STATUS(105),
    MODEL_INFO_DOWNLOAD_NO_HASH(106),
    MODEL_INFO_DOWNLOAD_CONNECTION_FAILED(107),
    NO_VALID_MODEL(108),
    LOCAL_MODEL_INVALID(109),
    REMOTE_MODEL_INVALID(110),
    REMOTE_MODEL_LOADER_ERROR(111),
    REMOTE_MODEL_LOADER_LOADS_NO_MODEL(112),
    SMART_REPLY_LANG_ID_DETECTAION_FAILURE(113),
    MODEL_NOT_REGISTERED(114),
    MODEL_TYPE_MISUSE(115),
    MODEL_HASH_MISMATCH(116),
    OPTIONAL_MODULE_NOT_AVAILABLE(HttpResponseStatus.SUCCESS_CREATED),
    OPTIONAL_MODULE_INIT_ERROR(HttpResponseStatus.SUCCESS_ACCEPTED),
    OPTIONAL_MODULE_INFERENCE_ERROR(HttpResponseStatus.SUCCESS_NON_AUTHORITATIVE_INFORMATION),
    OPTIONAL_MODULE_RELEASE_ERROR(HttpResponseStatus.SUCCESS_NO_CONTENT),
    OPTIONAL_TFLITE_MODULE_INIT_ERROR(HttpResponseStatus.SUCCESS_RESET_CONTENT),
    NATIVE_LIBRARY_LOAD_ERROR(HttpResponseStatus.SUCCESS_PARTIAL_CONTENT),
    OPTIONAL_MODULE_CREATE_ERROR(207),
    CAMERAX_SOURCE_ERROR(HttpResponseStatus.REDIRECTION_MOVED_PERMANENTLY),
    CAMERA1_SOURCE_CANT_START_ERROR(HttpResponseStatus.REDIRECTION_FOUND),
    CAMERA1_SOURCE_NO_SUITABLE_SIZE_ERROR(HttpResponseStatus.REDIRECTION_SEE_OTHER),
    CAMERA1_SOURCE_NO_SUITABLE_FPS_ERROR(HttpResponseStatus.REDIRECTION_NOT_MODIFIED),
    CAMERA1_SOURCE_NO_BYTE_SOURCE_FOUND_ERROR(HttpResponseStatus.REDIRECTION_USE_PROXY),
    CODE_SCANNER_UNAVAILABLE(HttpResponseStatus.ERROR_BAD_REQUEST),
    CODE_SCANNER_CANCELLED(HttpResponseStatus.ERROR_UNAUTHORIZED),
    CODE_SCANNER_CAMERA_PERMISSION_NOT_GRANTED(HttpResponseStatus.ERROR_PAYMENT_REQUIRED),
    CODE_SCANNER_APP_NAME_UNAVAILABLE(403),
    CODE_SCANNER_TASK_IN_PROGRESS(HttpResponseStatus.ERROR_NOT_FOUND),
    CODE_SCANNER_PIPELINE_INITIALIZATION_ERROR(HttpResponseStatus.ERROR_METHOD_NOT_ALLOWED),
    CODE_SCANNER_PIPELINE_INFERENCE_ERROR(HttpResponseStatus.ERROR_NOT_ACCEPTABLE),
    CODE_SCANNER_GOOGLE_PLAY_SERVICES_VERSION_TOO_OLD(HttpResponseStatus.ERROR_PROXY_AUTHENTICATION_REQUIRED),
    LOW_LIGHT_AUTO_EXPOSURE_COMPUTATION_FAILURE(HttpResponseStatus.ERROR_INTERNAL_SERVER_ERROR),
    LOW_LIGHT_IMAGE_CAPTURE_PROCESSING_FAILURE(HttpResponseStatus.ERROR_NOT_IMPLEMENTED),
    PERMISSION_DENIED(600),
    CANCELLED(601),
    GOOGLE_PLAY_SERVICES_VERSION_TOO_OLD(602),
    LOW_MEMORY(603),
    UNKNOWN_ERROR(9999);


    /* renamed from: a, reason: collision with root package name */
    private final int f5657a;

    @Override // Dd.O0
    public final int zza() {
        return this.f5657a;
    }

    Y6(int i10) {
        this.f5657a = i10;
    }
}
